import {
  Activity,
  CircleHelp,
  FileText,
  PanelsTopLeft,
  Search,
  Waypoints,
} from "lucide-react";
import {
  BOARD_CONTENTS_ROUTE,
  BOARD_FAQS_ROUTE,
  BOARD_GROUPS_ROUTE,
  BOARD_MANAGE_ROUTE,
  BOARD_POPULAR_RANK_ROUTE,
  BOARD_POPULAR_ROUTE,
  BOARD_QA_CONFIG_ROUTE,
  BOARD_WRITE_COUNT_ROUTE,
} from "../navigation-routes";
import type { NavigationGroup } from "../navigation-types";

export const boardsNavigationGroup: NavigationGroup = {
  id: "boards",
  label: "게시판관리",
  description: "레거시 menu300 게시판/콘텐츠 관리자 축입니다.",
  icon: PanelsTopLeft,
  items: [
    {
      to: BOARD_MANAGE_ROUTE,
      aliases: ["/boards"],
      label: "게시판관리",
      description: "게시판 목록, 상세, 생성, 수정, 삭제를 처리합니다.",
      icon: PanelsTopLeft,
      delivery: "implemented",
      legacySource: "adm/board_list.php",
    },
    {
      to: BOARD_GROUPS_ROUTE,
      label: "게시판그룹관리",
      description: "게시판 그룹, 그룹 멤버, 그룹 단위 권한을 관리합니다.",
      icon: Waypoints,
      delivery: "implemented",
      legacySource: "adm/boardgroup_list.php",
      note: "Rust 작업면은 `/admin/board-groups` CRUD와 그룹 회원 추가/삭제를 한 화면에서 다룹니다.",
    },
    {
      to: BOARD_POPULAR_ROUTE,
      label: "인기검색어관리",
      description: "인기검색어 목록과 관리 작업을 수행합니다.",
      icon: Search,
      delivery: "implemented",
      legacySource: "adm/popular_list.php",
      note: "Rust 작업면은 목록 조회와 기간 조건 초기화를 함께 다룹니다.",
    },
    {
      to: BOARD_POPULAR_RANK_ROUTE,
      label: "인기검색어순위",
      description: "인기검색어 랭킹 화면입니다.",
      icon: Activity,
      delivery: "implemented",
      legacySource: "adm/popular_rank.php",
      note: "Rust 작업면은 `/admin/popular/rank` 랭킹 카드가 먼저 보이도록 같은 페이지를 재배치합니다.",
    },
    {
      to: BOARD_QA_CONFIG_ROUTE,
      aliases: ["/settings/qa"],
      label: "1:1문의설정",
      description: "1:1 문의 기본 설정을 관리합니다.",
      icon: CircleHelp,
      delivery: "implemented",
      legacySource: "adm/qa_config.php",
    },
    {
      to: BOARD_CONTENTS_ROUTE,
      label: "내용관리",
      description: "정적 내용 페이지 목록과 상세를 관리합니다.",
      icon: FileText,
      delivery: "implemented",
      legacySource: "adm/contentlist.php",
      note: "Rust 작업면에서 내용 목록/상세/생성/수정/삭제를 한 화면에서 처리합니다.",
    },
    {
      to: BOARD_FAQS_ROUTE,
      label: "FAQ관리",
      description: "FAQ 마스터와 FAQ 문항을 함께 관리합니다.",
      icon: CircleHelp,
      delivery: "implemented",
      legacySource: "adm/faqmasterlist.php",
      note: "Rust 작업면에서 FAQ 마스터/문항 CRUD와 헤더·푸터 이미지 업로드를 함께 다룹니다.",
    },
    {
      to: BOARD_WRITE_COUNT_ROUTE,
      label: "글,댓글 현황",
      description: "글/댓글 집계 현황을 확인합니다.",
      icon: Activity,
      delivery: "implemented",
      legacySource: "adm/write_count.php",
      note: "Rust 작업면에서 기간/게시판 조건 기준 글·댓글 버킷 집계를 조회합니다.",
    },
  ],
};
