import {
  DatabaseZap,
  Info,
  Mail,
  MessageCircleMore,
  Palette,
  PanelsTopLeft,
  RefreshCw,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Trash2,
} from "lucide-react";
import {
  ENVIRONMENT_AUTH_ROUTE,
  ENVIRONMENT_BASIC_CONFIG_ROUTE,
  ENVIRONMENT_BROWSCAP_ROUTE,
  ENVIRONMENT_MAIL_TEST_ROUTE,
  ENVIRONMENT_MAINTENANCE_CACHE_ROUTE,
  ENVIRONMENT_MAINTENANCE_CAPTCHA_ROUTE,
  ENVIRONMENT_MAINTENANCE_MEMBER_LIST_ROUTE,
  ENVIRONMENT_MAINTENANCE_SESSION_ROUTE,
  ENVIRONMENT_MAINTENANCE_THUMBNAIL_ROUTE,
  ENVIRONMENT_MENUS_ROUTE,
  ENVIRONMENT_PHPINFO_ROUTE,
  ENVIRONMENT_POPUPS_ROUTE,
  ENVIRONMENT_THEME_ROUTE,
  ENVIRONMENT_VISIT_LOG_CONVERT_ROUTE,
} from "../navigation-routes";
import type { NavigationGroup } from "../navigation-types";

export const environmentNavigationGroup: NavigationGroup = {
  id: "environment",
  label: "환경설정",
  description: "레거시 menu100 환경설정 관리자 축입니다.",
  icon: SlidersHorizontal,
  items: [
    {
      to: ENVIRONMENT_BASIC_CONFIG_ROUTE,
      aliases: ["/settings/general"],
      label: "기본환경설정",
      description: "사이트 기본 설정, 회원 가입, 포인트 정책을 관리합니다.",
      icon: SlidersHorizontal,
      delivery: "implemented",
      legacySource: "adm/config_form.php",
    },
    {
      to: ENVIRONMENT_AUTH_ROUTE,
      aliases: ["/permissions"],
      label: "관리권한설정",
      description: "관리자별 접근 권한과 메뉴 권한을 관리합니다.",
      icon: ShieldCheck,
      delivery: "implemented",
      legacySource: "adm/auth_list.php",
      note: "Rust 작업면은 /admin/system/auths 호환 route를 사용합니다. OpenAPI에는 /admin/auth 계열도 함께 존재합니다.",
    },
    {
      to: ENVIRONMENT_THEME_ROUTE,
      label: "테마설정",
      description: "테마 목록, 현재 적용 테마, 상세 구성을 확인합니다.",
      icon: Palette,
      delivery: "implemented",
      legacySource: "adm/theme.php",
      note: "Rust 작업면에서 현재 PC/모바일 테마 설정, 설치 테마 목록, 개별 테마 상세를 함께 다룹니다.",
    },
    {
      to: ENVIRONMENT_MENUS_ROUTE,
      label: "메뉴설정",
      description: "사이트 메뉴 트리 조회, 수정, 재정렬을 다룹니다.",
      icon: PanelsTopLeft,
      delivery: "implemented",
      legacySource: "adm/menu_list.php",
      note: "Rust 작업면에서 메뉴 목록, 상세, 생성, 수정, 삭제, 순서 재정렬을 함께 다룹니다.",
    },
    {
      to: ENVIRONMENT_MAIL_TEST_ROUTE,
      label: "메일 테스트",
      description: "테스트 메일 발송과 관리자 메일 설정 점검 화면입니다.",
      icon: Mail,
      delivery: "implemented",
      legacySource: "adm/sendmail_test.php",
      note: "Rust 작업면은 비deprecated 시스템 경로 /admin/system/mails/test 기준으로 테스트 메일 발송을 수행합니다.",
    },
    {
      to: ENVIRONMENT_POPUPS_ROUTE,
      aliases: ["/operations/popups"],
      label: "팝업레이어관리",
      description: "운영 팝업 레이어를 생성, 수정, 삭제합니다.",
      icon: MessageCircleMore,
      delivery: "implemented",
      legacySource: "adm/newwinlist.php",
      note: "Rust 작업면은 /admin/system/popups 호환 route를 사용합니다. OpenAPI에는 /admin/popups 계열도 함께 존재합니다.",
    },
    {
      to: ENVIRONMENT_MAINTENANCE_SESSION_ROUTE,
      label: "세션파일 일괄삭제",
      description: "서버 세션 파일 purge 실행 메뉴입니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/session_file_delete.php",
      note: "Rust maintenance 작업면에서 session purge 액션으로 진입합니다.",
    },
    {
      to: ENVIRONMENT_MAINTENANCE_CACHE_ROUTE,
      label: "캐시파일 일괄삭제",
      description: "서버 캐시 파일 purge 실행 메뉴입니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/cache_file_delete.php",
      note: "Rust maintenance 작업면에서 cache purge 액션으로 진입합니다.",
    },
    {
      to: ENVIRONMENT_MAINTENANCE_CAPTCHA_ROUTE,
      label: "캡챠파일 일괄삭제",
      description: "캡차 이미지/보조 파일 purge 실행 메뉴입니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/captcha_file_delete.php",
      note: "Rust maintenance 작업면에서 captcha purge 액션으로 진입합니다.",
    },
    {
      to: ENVIRONMENT_MAINTENANCE_THUMBNAIL_ROUTE,
      label: "썸네일파일 일괄삭제",
      description: "썸네일 캐시 파일 purge 실행 메뉴입니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/thumbnail_file_delete.php",
      note: "Rust maintenance 작업면에서 thumbnail purge 액션으로 진입합니다.",
    },
    {
      to: ENVIRONMENT_MAINTENANCE_MEMBER_LIST_ROUTE,
      label: "회원관리파일 일괄삭제",
      description: "회원관리파일 export 산출물 purge 실행 메뉴입니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/member_list_file_delete.php",
      note: "Rust maintenance 작업면에서 member-list purge 액션으로 진입합니다.",
    },
    {
      to: ENVIRONMENT_PHPINFO_ROUTE,
      label: "phpinfo()",
      description: "현재 PHP 런타임과 확장 모듈 정보를 확인합니다.",
      icon: Info,
      delivery: "implemented",
      legacySource: "adm/phpinfo.php",
      note: "Rust 작업면에서 PHP 버전, ini 경로, 확장 모듈 수와 phpinfo HTML 원문을 함께 보여줍니다.",
    },
    {
      to: ENVIRONMENT_BROWSCAP_ROUTE,
      label: "Browscap 업데이트",
      description: "Browscap 상태 조회와 업데이트 실행 메뉴입니다.",
      icon: RefreshCw,
      delivery: "implemented",
      legacySource: "adm/browscap.php",
      note: "Rust 작업면에서 plugin/cache 상태 조회와 캐시 업데이트를 함께 수행합니다.",
    },
    {
      to: ENVIRONMENT_VISIT_LOG_CONVERT_ROUTE,
      label: "접속로그 변환",
      description: "Browscap 기반 접속 로그 변환 작업을 실행합니다.",
      icon: RefreshCw,
      delivery: "implemented",
      legacySource: "adm/browscap_convert.php",
      note: "Rust 작업면은 Browscap 상태와 변환 배치 실행기를 같이 보여주되, 현재 메뉴에서는 변환 카드가 먼저 강조됩니다.",
    },
    {
      to: "/environment/db-upgrade",
      label: "DB업그레이드",
      description: "스키마 업그레이드 실행기입니다.",
      icon: DatabaseZap,
      delivery: "api_excluded",
      legacySource: "adm/dbupgrade.php",
      note: "REST로 직접 노출하지 않고 웹/CLI 내부 실행기로 유지하는 항목입니다.",
    },
    {
      to: "/environment/services",
      label: "부가서비스",
      description: "외부 서비스/홍보 링크 모음 메뉴입니다.",
      icon: Sparkles,
      delivery: "api_excluded",
      legacySource: "adm/service.php",
      note: "제품 기능 계약 대상이 아니라 API 이관 대상에서 제외된 항목입니다.",
    },
  ],
};
