import {
  Activity,
  FileText,
  MessageSquareMore,
  Send,
  Smile,
  Users,
} from "lucide-react";
import {
  SMS_CONFIG_ROUTE,
  SMS_CONTACT_FILES_ROUTE,
  SMS_CONTACT_GROUPS_ROUTE,
  SMS_CONTACTS_ROUTE,
  SMS_HISTORY_BATCHES_ROUTE,
  SMS_HISTORY_DELIVERIES_ROUTE,
  SMS_MEMBER_SYNC_ROUTE,
  SMS_MESSAGES_ROUTE,
  SMS_TEMPLATE_GROUPS_ROUTE,
  SMS_TEMPLATES_ROUTE,
} from "../navigation-routes";
import type { NavigationGroup } from "../navigation-types";

export const smsNavigationGroup: NavigationGroup = {
  id: "sms",
  label: "SMS 관리",
  description: "레거시 menu900 SMS 관리자 축입니다.",
  icon: MessageSquareMore,
  items: [
    {
      to: SMS_CONFIG_ROUTE,
      aliases: ["/settings/sms"],
      label: "SMS 기본설정",
      description: "SMS 공급자 설정과 회신번호, 기본 정책을 관리합니다.",
      icon: MessageSquareMore,
      delivery: "implemented",
      legacySource: "adm/sms_admin/config.php",
    },
    {
      to: SMS_MEMBER_SYNC_ROUTE,
      label: "회원정보업데이트",
      description: "회원 연락처를 SMS 주소록으로 동기화합니다.",
      icon: Users,
      delivery: "implemented",
      legacySource: "adm/sms_admin/member_update.php",
    },
    {
      to: SMS_MESSAGES_ROUTE,
      label: "문자 보내기",
      description: "SMS/LMS 발송 작업면입니다.",
      icon: Send,
      delivery: "implemented",
      legacySource: "adm/sms_admin/sms_write.php",
      note: "템플릿 선택, 직접 입력, 그룹/연락처/레벨/수동 대상 조합과 예약 발송을 함께 다룹니다.",
    },
    {
      to: SMS_HISTORY_BATCHES_ROUTE,
      label: "전송내역-건별",
      description: "배치 기준 전송 이력 목록과 재전송 흐름입니다.",
      icon: Activity,
      delivery: "implemented",
      legacySource: "adm/sms_admin/history_list.php",
      note: "배치 목록, 상세 로그, 실패건/전체 재전송을 같은 작업면에서 처리합니다.",
    },
    {
      to: SMS_HISTORY_DELIVERIES_ROUTE,
      label: "전송내역-번호별",
      description: "번호 기준 전송 이력 조회 메뉴입니다.",
      icon: Activity,
      delivery: "implemented",
      legacySource: "adm/sms_admin/history_num.php",
      note: "이름/번호/주소록 번호 기준 번호별 전송 이력을 조회합니다.",
    },
    {
      to: SMS_TEMPLATE_GROUPS_ROUTE,
      label: "이모티콘 그룹",
      description: "이모티콘 템플릿 그룹을 관리합니다.",
      icon: Smile,
      delivery: "implemented",
      legacySource: "adm/sms_admin/form_group.php",
      note: "그룹 CRUD, 이동, 비우기와 템플릿 목록 연동을 한 화면에서 다룹니다.",
    },
    {
      to: SMS_TEMPLATES_ROUTE,
      label: "이모티콘 관리",
      description: "이모티콘 템플릿 목록과 상세를 관리합니다.",
      icon: Smile,
      delivery: "implemented",
      legacySource: "adm/sms_admin/form_list.php",
      note: "템플릿 CRUD, 그룹 필터, 검색, 일괄 이동/삭제를 지원합니다.",
    },
    {
      to: SMS_CONTACT_GROUPS_ROUTE,
      label: "휴대폰번호 그룹",
      description: "연락처 그룹 목록과 정렬을 관리합니다.",
      icon: Users,
      delivery: "implemented",
      legacySource: "adm/sms_admin/num_group.php",
      note: "그룹 CRUD, 이동, 비우기와 주소록 연동 작업면을 제공합니다.",
    },
    {
      to: SMS_CONTACTS_ROUTE,
      label: "휴대폰번호 관리",
      description: "개별 연락처 목록과 CRUD를 처리합니다.",
      icon: Users,
      delivery: "implemented",
      legacySource: "adm/sms_admin/num_book.php",
      note: "연락처 CRUD와 일괄 허용/거부/이동/복사/삭제를 지원합니다.",
    },
    {
      to: SMS_CONTACT_FILES_ROUTE,
      label: "휴대폰번호 파일",
      description: "연락처 파일 import/export 작업면입니다.",
      icon: FileText,
      delivery: "implemented",
      legacySource: "adm/sms_admin/num_book_file.php",
      note: "CSV/XLSX 업로드, 텍스트 가져오기, 내보내기 미리보기를 제공합니다.",
    },
  ],
};
