from __future__ import annotations

import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

MODULE_PATH = Path(__file__).resolve().parents[1] / "prepare_consumers.py"
SPEC = importlib.util.spec_from_file_location("prepare_consumers", MODULE_PATH)
assert SPEC and SPEC.loader
consumers = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = consumers
SPEC.loader.exec_module(consumers)


def git(cwd: Path, *args: str) -> str:
    completed = subprocess.run(
        ("git", *args),
        cwd=cwd,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return completed.stdout.strip()


class ConsumerFixture:
    def __init__(self, base: Path) -> None:
        self.root = base / "fleet"
        self.web = self.root / consumers.WEB_RELATIVE
        self.desktop = self.root / consumers.DESKTOP_RELATIVE
        self.web.mkdir(parents=True)
        git(self.root, "init", "-b", "main")
        git(self.root, "config", "user.name", "Consumer Test")
        git(self.root, "config", "user.email", "consumer@example.invalid")

        (self.web / "package.json").write_text(
            json.dumps(
                {
                    "name": "fixture-admin",
                    "private": True,
                    "packageManager": "bun@1.2.3",
                    "devDependencies": {
                        "eslint": "1.0.0",
                        "typescript": "1.0.0",
                        "vitest": "1.0.0",
                    },
                }
            )
            + "\n",
            encoding="utf-8",
        )
        (self.web / "bun.lock").write_text('{"lockfileVersion":1}\n', encoding="utf-8")
        (self.desktop / "Cargo.toml").write_text(
            '[workspace]\nresolver = "2"\nmembers = []\n',
            encoding="utf-8",
        )
        (self.desktop / "Cargo.lock").write_text(
            "# This file is automatically @generated by Cargo.\nversion = 4\n",
            encoding="utf-8",
        )
        requirements = self.desktop / "scripts/requirements-audit.txt"
        requirements.parent.mkdir(parents=True)
        requirements.write_text("PyYAML==6.0.3\n", encoding="utf-8")
        audit_requirements = self.root / consumers.AUDIT_REQUIREMENTS_RELATIVE
        audit_requirements.parent.mkdir(parents=True)
        audit_requirements.write_text("PyYAML==6.0.3\n", encoding="utf-8")
        (self.root / ".gitignore").write_text(
            ".cache/\nnode_modules/\ntarget/\n",
            encoding="utf-8",
        )
        git(self.root, "add", ".")
        git(self.root, "commit", "-m", "fixture")

        self.log = base / "tool-log.jsonl"
        self.bun = base / "fake-bun"
        self.cargo = base / "fake-cargo"
        self.python = base / "fake-python"
        self.venv_python_template = base / "fake-venv-python-template"
        self.bun.write_text(
            "#!/usr/bin/env python3\n"
            "import json, pathlib, sys\n"
            f"log=pathlib.Path({str(self.log)!r})\n"
            "with log.open('a') as out: out.write(json.dumps({'tool':'bun','args':sys.argv[1:]})+'\\n')\n"
            "if sys.argv[1:] == ['--version']:\n"
            " print('1.2.3'); raise SystemExit(0)\n"
            "if sys.argv[1:] != ['install','--frozen-lockfile','--ignore-scripts']:\n"
            " raise SystemExit(41)\n"
            "bin_root=pathlib.Path.cwd()/'node_modules/.bin'; bin_root.mkdir(parents=True, exist_ok=True)\n"
            "for name in ('tsc','eslint','vitest'):\n"
            " target=bin_root/name; target.write_text('#!/bin/sh\\nexit 0\\n'); target.chmod(0o755)\n",
            encoding="utf-8",
        )
        self.cargo.write_text(
            "#!/usr/bin/env python3\n"
            "import json, os, pathlib, sys\n"
            f"log=pathlib.Path({str(self.log)!r})\n"
            "args=sys.argv[1:]\n"
            "with log.open('a') as out: out.write(json.dumps({'tool':'cargo','args':args,'offline':os.environ.get('CARGO_NET_OFFLINE')})+'\\n')\n"
            "if args == ['--version']:\n"
            " print('cargo 9.9.9 (fixture 2099-01-01)'); raise SystemExit(0)\n"
            "if args == ['fetch','--locked','--manifest-path','Cargo.toml']:\n"
            " raise SystemExit(0)\n"
            "expected=['metadata','--locked','--offline','--format-version','1','--manifest-path','Cargo.toml']\n"
            "if args == expected and os.environ.get('CARGO_NET_OFFLINE') == 'true':\n"
            " print('{\"packages\":[],\"workspace_members\":[]}'); raise SystemExit(0)\n"
            "raise SystemExit(42)\n",
            encoding="utf-8",
        )
        self.venv_python_template.write_text(
            "#!/usr/bin/env python3\n"
            "import json, pathlib, re, sys\n"
            f"log=pathlib.Path({str(self.log)!r})\n"
            "args=sys.argv[1:]; venv=pathlib.Path(__file__).resolve().parents[1]\n"
            "with log.open('a') as out: out.write(json.dumps({'tool':'python-venv','args':args})+'\\n')\n"
            "marker=venv/'pyyaml-version.txt'; yaml_file=venv/'lib/site-packages/yaml/__init__.py'\n"
            "expected_prefix=['-m','pip','install','--disable-pip-version-check','--no-deps','--requirement']\n"
            "if args[:6] == expected_prefix and len(args) == 7:\n"
            " text=pathlib.Path(args[6]).read_text(); match=re.search(r'^PyYAML==([^\\\\s]+)$',text,re.M)\n"
            " if not match: raise SystemExit(51)\n"
            " marker.write_text(match.group(1)); yaml_file.parent.mkdir(parents=True,exist_ok=True)\n"
            " yaml_file.write_text('__version__ = '+repr(match.group(1))+'\\\\n'); raise SystemExit(0)\n"
            "if args and args[0] == '-c':\n"
            " version=marker.read_text().strip()\n"
            " print(json.dumps({'version':'3.12.9','executable':str(pathlib.Path(__file__).resolve()),"
            "'prefix':str(venv),'base_prefix':str(venv.parent/'fixture-base'),"
            "'pyyaml_metadata_version':version,'yaml_version':version,'yaml_file':str(yaml_file.resolve())},sort_keys=True));"
            " raise SystemExit(0)\n"
            "raise SystemExit(52)\n",
            encoding="utf-8",
        )
        self.python.write_text(
            "#!/usr/bin/env python3\n"
            "import json, pathlib, shutil, sys\n"
            f"log=pathlib.Path({str(self.log)!r}); template=pathlib.Path({str(self.venv_python_template)!r})\n"
            f"identity=pathlib.Path({str(self.python)!r}).resolve()\n"
            "args=sys.argv[1:]\n"
            "with log.open('a') as out: out.write(json.dumps({'tool':'python-system','args':args})+'\\n')\n"
            "if args and args[0] == '-c':\n"
            " print(json.dumps({'version':'3.12.9','executable':str(identity),'implementation':'CPython'},sort_keys=True));"
            " raise SystemExit(0)\n"
            "if args[:2] == ['-m','venv'] and len(args) == 3:\n"
            " target=pathlib.Path.cwd()/args[2]; executable=target/'bin/python'; executable.parent.mkdir(parents=True)\n"
            " shutil.copyfile(template,executable); executable.chmod(0o755); raise SystemExit(0)\n"
            "raise SystemExit(53)\n",
            encoding="utf-8",
        )
        self.bun.chmod(0o755)
        self.cargo.chmod(0o755)
        self.python.chmod(0o755)

    def calls(self) -> list[dict[str, object]]:
        if not self.log.exists():
            return []
        return [json.loads(line) for line in self.log.read_text().splitlines()]


class PrepareConsumersTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.fixture = ConsumerFixture(Path(self.temporary.name))

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def prepare(self) -> dict[str, object]:
        return consumers.prepare(
            self.fixture.root,
            str(self.fixture.bun),
            str(self.fixture.cargo),
            str(self.fixture.python),
        )

    def verify(self) -> dict[str, object]:
        return consumers.verify(
            self.fixture.root,
            str(self.fixture.bun),
            str(self.fixture.cargo),
            str(self.fixture.python),
        )

    def prepare_audit(self) -> dict[str, object]:
        return consumers.prepare_audit(
            self.fixture.root,
            str(self.fixture.python),
        )

    def verify_audit(self) -> dict[str, object]:
        return consumers.verify_audit(
            self.fixture.root,
            str(self.fixture.python),
        )

    def test_routine_audit_runtime_never_invokes_desktop_bun_or_cargo(self) -> None:
        payload = self.prepare_audit()
        self.assertEqual(consumers.AUDIT_MANIFEST_KIND, payload["kind"])
        self.assertEqual(
            consumers.AUDIT_MANIFEST_RELATIVE.as_posix(),
            self.verify_audit()["manifest"],
        )
        calls = self.fixture.calls()
        self.assertFalse(any(call["tool"] in {"bun", "cargo"} for call in calls))
        self.assertEqual({"python"}, set(payload["tools"]))
        self.assertEqual(
            consumers.AUDIT_REQUIREMENTS_RELATIVE.as_posix(),
            payload["inputs"]["python_audit_requirements"]["path"],
        )

    def test_prepare_uses_locked_commands_and_verify_is_offline_only(self) -> None:
        payload = self.prepare()
        self.assertEqual("prepared", payload["status"])
        calls_after_prepare = self.fixture.calls()
        self.assertIn(
            {"tool": "bun", "args": ["install", "--frozen-lockfile", "--ignore-scripts"]},
            calls_after_prepare,
        )
        self.assertIn(
            {
                "tool": "cargo",
                "args": ["fetch", "--locked", "--manifest-path", "Cargo.toml"],
                "offline": None,
            },
            calls_after_prepare,
        )
        python_installs = [
            call
            for call in calls_after_prepare
            if call["tool"] == "python-venv"
            and call["args"][:3] == ["-m", "pip", "install"]
        ]
        self.assertEqual(1, len(python_installs))
        self.assertIn("--no-deps", python_installs[0]["args"])
        self.assertIn("--requirement", python_installs[0]["args"])
        self.assertEqual("3.12.9", payload["tools"]["python"]["version"])
        self.assertEqual("3.12.9", payload["python_audit"]["python_version"])
        self.assertEqual("6.0.3", payload["python_audit"]["pyyaml_version"])
        self.assertEqual(
            consumers.sha256_file(self.fixture.desktop / "scripts/requirements-audit.txt"),
            payload["inputs"]["python_audit_requirements"]["sha256"],
        )

        result = self.verify()
        self.assertEqual("verified", result["status"])
        verify_calls = self.fixture.calls()[len(calls_after_prepare):]
        self.assertFalse(
            any(
                call["args"][0] in {"install", "fetch"}
                or call["args"][:3] == ["-m", "pip", "install"]
                or call["args"][:2] == ["-m", "venv"]
                for call in verify_calls
            )
        )
        metadata = [call for call in verify_calls if call["args"][0] == "metadata"]
        self.assertEqual(1, len(metadata))
        self.assertIn("--offline", metadata[0]["args"])
        self.assertEqual("true", metadata[0]["offline"])

    def test_lock_and_head_drift_are_rejected_before_offline_metadata(self) -> None:
        self.prepare()
        calls_before = len(self.fixture.calls())
        (self.fixture.web / "bun.lock").write_text('{"lockfileVersion":2}\n', encoding="utf-8")
        with self.assertRaisesRegex(RuntimeError, "repository must be clean|input drift"):
            self.verify()
        self.assertEqual(calls_before, len(self.fixture.calls()))

        git(self.fixture.root, "add", str(consumers.BUN_LOCK_RELATIVE))
        git(self.fixture.root, "commit", "-m", "change lock")
        with self.assertRaisesRegex(RuntimeError, "stale for the current Git HEAD"):
            self.verify()

    def test_missing_or_mutated_local_binary_is_rejected(self) -> None:
        self.prepare()
        bin_path = self.fixture.web / "node_modules/.bin/tsc"
        bin_path.unlink()
        with self.assertRaisesRegex(RuntimeError, "binary is missing"):
            self.verify()

        self.prepare()
        bin_path.write_text("#!/bin/sh\nexit 9\n", encoding="utf-8")
        bin_path.chmod(0o755)
        with self.assertRaisesRegex(RuntimeError, "local binary drift"):
            self.verify()

    def test_python_requirements_and_venv_mutations_are_rejected(self) -> None:
        self.prepare()
        marker = self.fixture.root / consumers.PYTHON_VENV_RELATIVE / "pyyaml-version.txt"
        marker.write_text("6.0.4", encoding="utf-8")
        with self.assertRaisesRegex(RuntimeError, "PyYAML installed version mismatch"):
            self.verify()

        self.prepare()
        venv_python = self.fixture.root / consumers.PYTHON_VENV_RELATIVE / "bin/python"
        venv_python.unlink()
        with self.assertRaisesRegex(RuntimeError, "venv executable is missing"):
            self.verify()

        self.prepare()
        requirements = self.fixture.root / consumers.PYTHON_REQUIREMENTS_RELATIVE
        requirements.write_text("PyYAML>=6.0.3\n", encoding="utf-8")
        with self.assertRaisesRegex(RuntimeError, "repository must be clean|input drift"):
            self.verify()

    def test_python_venv_is_recreated_without_stale_files_and_rejects_symlink(self) -> None:
        self.prepare()
        venv = self.fixture.root / consumers.PYTHON_VENV_RELATIVE
        stale = venv / "stale-package.py"
        stale.write_text("stale\n", encoding="utf-8")
        self.prepare()
        self.assertFalse(stale.exists())

        external = Path(self.temporary.name) / "external-venv"
        venv.rename(external)
        os.symlink(external, venv)
        with self.assertRaisesRegex(RuntimeError, "symlink"):
            self.verify()

    def test_tool_version_drift_and_cache_symlink_are_rejected(self) -> None:
        self.prepare()
        self.fixture.bun.write_text(
            "#!/bin/sh\n[ \"$1\" = \"--version\" ] && echo 2.0.0 && exit 0\nexit 43\n",
            encoding="utf-8",
        )
        self.fixture.bun.chmod(0o755)
        with self.assertRaisesRegex(RuntimeError, "Bun version mismatch|tool version drift"):
            self.verify()

        external = Path(self.temporary.name) / "external-cache"
        cache = self.fixture.root / ".cache"
        if cache.exists():
            cache.rename(external)
        else:
            external.mkdir()
        os.symlink(external, cache)
        with self.assertRaisesRegex(RuntimeError, "cache path symlink"):
            consumers.prepare(
                self.fixture.root,
                str(self.fixture.bun),
                str(self.fixture.cargo),
                str(self.fixture.python),
            )


if __name__ == "__main__":
    unittest.main()
