// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemMaintenanceResult } from "./AdminSystemMaintenanceResult";
import type { Meta } from "./Meta";

export type AdminSystemMaintenanceResponse = { data: AdminSystemMaintenanceResult, meta: Meta, };
