// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemThemeListMeta = { server_time: string, version: string, total?: number, request_id?: string, correlation_id?: string, server_request_id?: string, };
