// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemTheme } from "./AdminSystemTheme";
import type { AdminSystemThemeListMeta } from "./AdminSystemThemeListMeta";

export type AdminSystemThemeListResponse = { data: Array<AdminSystemTheme>, meta: AdminSystemThemeListMeta, };
