// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthAssignmentInput } from "./AdminAuthAssignmentInput";

export type AdminAuthUpsertRequest = { auths?: Array<AdminAuthAssignmentInput>, au_menu?: string, au_auth?: string, };
