// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLayoutWidgetCreateRequest = { widget_id?: string, type: string, title?: string, order?: number, config?: Record<string, unknown>, style?: Record<string, unknown>, };
