// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemThemeConfig } from "./AdminSystemThemeConfig";
import type { Meta } from "./Meta";

export type AdminSystemThemeConfigResponse = { data: AdminSystemThemeConfig, meta: Meta, };
