// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMemberMediaDeleteResult = { mb_id: string, storage: string, relative_path: string, url: string, deleted: boolean, };
