// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemTheme = { id: string, path: string, theme_name: string, theme_uri: string, maker: string, maker_uri: string, version: string, detail: string, license: string, license_uri: string, readme_path: string | null, theme_config_path: string | null, screenshot_path: string | null, set_default_skin: boolean, preview_board_skin: string, preview_mobile_board_skin: string, is_active: boolean, is_mobile_active: boolean, theme_config: Record<string, unknown>, };
