// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsMessageBatchDetail } from "./AdminSmsMessageBatchDetail";
import type { Meta } from "./Meta";

export type AdminSmsMessageBatchDetailResponse = { data: AdminSmsMessageBatchDetail, meta: Meta, };
