// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPushSendResult } from "./AdminPushSendResult";
import type { Meta } from "./Meta";

export type AdminPushSendResponse = { data: AdminPushSendResult, meta: Meta, };
