// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailTestResult = { ma_id: number | null, template_used: boolean, mail_enabled: boolean, sent: boolean, to: string, };
