// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplateGroupClearResult } from "./AdminSmsTemplateGroupClearResult";
import type { Meta } from "./Meta";

export type AdminSmsTemplateGroupClearResponse = { data: AdminSmsTemplateGroupClearResult, meta: Meta, };
