// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateGroupCreateRequest = { fg_name: string, fg_member?: number, };
