// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemPhpInfo } from "./AdminSystemPhpInfo";
import type { Meta } from "./Meta";

export type AdminSystemPhpInfoResponse = { data: AdminSystemPhpInfo, meta: Meta, };
