// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailTestResult } from "./AdminMailTestResult";
import type { Meta } from "./Meta";

export type AdminMailTestResponse = { data: AdminMailTestResult, meta: Meta, };
