// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemPermission = { mb_id: string, au_menu: string, au_auth: string, mb_name?: string | null, mb_nick?: string | null, };
