// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMember } from "./AdminMember";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminMemberListResponse = { data: Array<AdminMember>, pagination: Pagination, meta: Meta, };
