// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplateBatchResult } from "./AdminSmsTemplateBatchResult";
import type { Meta } from "./Meta";

export type AdminSmsTemplateBatchResponse = { data: AdminSmsTemplateBatchResult, meta: Meta, };
