// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsDelivery = { hs_no: number, wr_no: number | null, wr_renum: number | null, bg_no: number | null, bg_name: string | null, mb_id: string | null, bk_no: number | null, hs_name: string | null, hs_hp: string | null, hs_datetime: string | null, hs_flag: number | null, hs_code: string | null, hs_memo: string | null, hs_log: string | null, wr_message: string | null, wr_datetime: string | null, wr_booking: string | null, };
