// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminNewPostsDeleteResult } from "./AdminNewPostsDeleteResult";
import type { Meta } from "./Meta";

export type AdminNewPostsDeleteResponse = { data: AdminNewPostsDeleteResult, meta: Meta, };
