// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminDashboardData } from "./AdminDashboardData";
import type { Meta } from "./Meta";

export type AdminDashboardResponse = { data: AdminDashboardData, meta: Meta, };
