// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemQaConfig } from "./AdminSystemQaConfig";
import type { Meta } from "./Meta";

export type AdminSystemQaConfigResponse = { data: AdminSystemQaConfig, meta: Meta, };
