// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminQaBulkDeleteResult } from "./AdminQaBulkDeleteResult";
import type { Meta } from "./Meta";

export type AdminQaBulkDeleteResponse = { data: AdminQaBulkDeleteResult, meta: Meta, };
