// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsSendResult } from "./AdminSmsSendResult";
import type { Meta } from "./Meta";

export type AdminSmsSendResponse = { data: AdminSmsSendResult, meta: Meta, };
