// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLayoutWidget } from "./AdminLayoutWidget";

export type AdminLayoutSaveRequest = { title?: string, widgets: Array<AdminLayoutWidget>, };
