// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsMemberSyncSummary } from "./AdminSmsMemberSyncSummary";

export type AdminSmsMemberSyncResult = { datetime: string | null, summary: AdminSmsMemberSyncSummary, };
