// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactBatchResult } from "./AdminSmsContactBatchResult";
import type { Meta } from "./Meta";

export type AdminSmsContactBatchResponse = { data: AdminSmsContactBatchResult, meta: Meta, };
