// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminWriteCountItem } from "./AdminWriteCountItem";
import type { AdminWriteCountSummary } from "./AdminWriteCountSummary";

export type AdminWriteCountStats = { period: string, date_from: string, date_to: string, bo_table: string | null, summary: AdminWriteCountSummary, items: Array<AdminWriteCountItem>, };
