// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthAssignment } from "./AdminAuthAssignment";

export type AdminAuthMember = { mb_id: string, mb_name: string, mb_nick: string, auths: Array<AdminAuthAssignment>, };
