// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSchemaDetail } from "./AdminSchemaDetail";
import type { Meta } from "./Meta";

export type AdminSchemaDetailResponse = { data: AdminSchemaDetail, meta: Meta, };
