// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailSendRequest = { ma_id?: number, subject?: string, content?: string, target_type: string, level_min?: number, level_max?: number, gr_id?: string, member_id_from?: string, member_id_to?: string, email_contains?: string, mb_ids?: Array<string>, mailling_only?: boolean, dry_run?: boolean, };
