// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsMessageBatch } from "./AdminSmsMessageBatch";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminSmsMessageBatchListResponse = { data: Array<AdminSmsMessageBatch>, pagination: Pagination, meta: Meta, };
