// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContact } from "./AdminSmsContact";
import type { AdminSmsContactListResponseMeta } from "./AdminSmsContactListResponseMeta";
import type { Pagination } from "./Pagination";

export type AdminSmsContactListResponse = { data: Array<AdminSmsContact>, pagination: Pagination, meta: AdminSmsContactListResponseMeta, };
