// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBoard } from "./AdminBoard";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminBoardListResponse = { data: Array<AdminBoard>, pagination: Pagination, meta: Meta, };
