// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPopularItem } from "./AdminPopularItem";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminPopularListResponse = { data: Array<AdminPopularItem>, pagination: Pagination, meta: Meta, };
