// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminConfig } from "./AdminConfig";
import type { Meta } from "./Meta";

export type AdminConfigResponse = { data: AdminConfig, meta: Meta, };
