// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMemberUploadFile } from "./AdminMemberUploadFile";

export type AdminMemberImageUploadRequest = { file?: AdminMemberUploadFile, image?: AdminMemberUploadFile, mb_img?: AdminMemberUploadFile, };
