// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplate } from "./AdminSmsTemplate";
import type { Meta } from "./Meta";

export type AdminSmsTemplateDetailResponse = { data: AdminSmsTemplate, meta: Meta, };
