// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactGroupClearResult } from "./AdminSmsContactGroupClearResult";
import type { Meta } from "./Meta";

export type AdminSmsContactGroupClearResponse = { data: AdminSmsContactGroupClearResult, meta: Meta, };
