// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemTheme } from "./AdminSystemTheme";
import type { Meta } from "./Meta";

export type AdminSystemThemeDetailResponse = { data: AdminSystemTheme, meta: Meta, };
