// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactImportResult = { total_count: number, invalid_count: number, duplicate_count: number, importable_count: number, imported_count: number, dry_run: boolean, duplicate_phones: Array<string>, importable_phones: Array<string>, };
