// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLayoutDetail } from "./AdminLayoutDetail";
import type { Meta } from "./Meta";

export type AdminLayoutDetailResponse = { data: AdminLayoutDetail, meta: Meta, };
