// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsDelivery } from "./AdminSmsDelivery";
import type { AdminSmsDuplicateSummary } from "./AdminSmsDuplicateSummary";
import type { AdminSmsRetryBatch } from "./AdminSmsRetryBatch";
import type { Pagination } from "./Pagination";

export type AdminSmsMessageBatchDetail = { wr_no: number, wr_renum: number, wr_reply: string | null, wr_message: string | null, wr_booking: string | null, wr_total: number, wr_re_total: number, wr_success: number, wr_failure: number, wr_datetime: string | null, wr_memo: string | null, duplicate_summary: AdminSmsDuplicateSummary | null, retry_batches: Array<AdminSmsRetryBatch>, deliveries: Array<AdminSmsDelivery>, deliveries_pagination: Pagination, };
