// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMemberMediaUploadResult } from "./AdminMemberMediaUploadResult";
import type { Meta } from "./Meta";

export type AdminMemberMediaUploadResponse = { data: AdminMemberMediaUploadResult, meta: Meta, };
