// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsDelivery } from "./AdminSmsDelivery";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminSmsDeliveryListResponse = { data: Array<AdminSmsDelivery>, pagination: Pagination, meta: Meta, };
