// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsManualTarget } from "./AdminSmsManualTarget";

export type AdminSmsMessageCreateRequest = { message?: string, wr_message?: string, template_id?: number, fo_no?: number, reply?: string, wr_reply?: string, booking_at?: string, group_ids?: Array<number>, contact_ids?: Array<number>, member_levels?: Array<number>, manual_targets?: Array<AdminSmsManualTarget>, };
