// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardSummary } from "./BoardSummary";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type BoardListResponse = { data: Array<BoardSummary>, pagination: Pagination, meta: Meta, };
