// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BoardSummary = { bo_table: string, bo_subject: string, gr_id: string, gr_subject: string, bo_read_level: number, bo_write_level: number, bo_comment_level: number, bo_use_category: number, bo_category_list: string, bo_count_write: number, bo_count_comment: number, bo_use_secret: number, bo_use_dhtml_editor: number, bo_upload_count: number, bo_upload_size: number, };
