// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Comment = { wr_id: number, wr_parent: number, wr_comment: number, wr_comment_reply: string, wr_content: string, mb_id: string, wr_name: string, wr_datetime: string, };
