// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Config } from "./Config";
import type { Meta } from "./Meta";

export type ConfigResponse = { data: Config, meta: Meta, };
