// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentUpdateRequest = { co_subject?: string, co_html?: number, co_content?: string, co_mobile_content?: string, co_include_head?: string, co_include_tail?: string, co_tag_filter_use?: number, co_skin?: string, co_mobile_skin?: string, };
