// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthStartRequest = { flow?: string, callback_url: string, state?: string, scopes?: Array<string>, metadata?: Record<string, unknown>, scenario?: string, };
