// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthLinkedMember } from "./ExternalAuthLinkedMember";

export type ExternalAuthLinkage = { status: string, reason: string, linked_member?: ExternalAuthLinkedMember | null, candidate_member?: ExternalAuthLinkedMember | null, };
