// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthLinkRecord } from "./ExternalAuthLinkRecord";
import type { Meta } from "./Meta";

export type ExternalAuthLinkResponse = { data: ExternalAuthLinkRecord, meta?: Meta, };
