// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthRegistrationResponseData } from "./ExternalAuthRegistrationResponseData";
import type { Meta } from "./Meta";

export type ExternalAuthRegistrationResponse = { data: ExternalAuthRegistrationResponseData, meta?: Meta, };
