// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthClaimResponseData } from "./ExternalAuthClaimResponseData";
import type { Meta } from "./Meta";

export type ExternalAuthClaimResponse = { data: ExternalAuthClaimResponseData, meta?: Meta, };
