// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthProviderUser = { provider_user_id?: string, email?: string, display_name?: string, };
