// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthSessionPayload } from "./ExternalAuthSessionPayload";
import type { Meta } from "./Meta";

export type ExternalAuthSessionResponse = { data: ExternalAuthSessionPayload, meta?: Meta, };
