// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthProviderDefinition = { provider: string, label: string, mode: string, description: string, flows: Array<string>, sandbox_available: boolean, replay_supported: boolean, runtime_replay_enabled: boolean, };
