// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqImage } from "./FaqImage";
import type { Meta } from "./Meta";

export type FaqImageResponse = { data: FaqImage, meta: Meta, };
