// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqItem } from "./FaqItem";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type FaqListResponse = { data: Array<FaqItem>, pagination: Pagination, meta: Meta, };
