// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FaqMasterUpdateRequest = { fm_subject?: string, fm_order?: number, fm_head_html?: string, fm_tail_html?: string, fm_mobile_head_html?: string, fm_mobile_tail_html?: string, };
