// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqMasterDetail } from "./FaqMasterDetail";
import type { Meta } from "./Meta";

export type FaqMasterDetailResponse = { data: FaqMasterDetail, meta: Meta, };
