// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Group } from "./Group";
import type { Meta } from "./Meta";

export type GroupDetailResponse = { data: Group, meta: Meta, };
