// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MenuUpdateRequest = { me_code?: string, me_name?: string, me_link?: string, me_target?: string, me_order?: number, me_use?: number, me_mobile_use?: number, };
