// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Meta = { request_id?: string, correlation_id?: string, server_request_id?: string, server_time?: string, version?: string, error_code?: string, error_category?: string, fault_domain?: string, owner?: string, retryable?: boolean, user_actionable?: boolean, };
