// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../g5-admin-models/bindings/serde_json/JsonValue";
import type { PluginBoardRewardCommand } from "./PluginBoardRewardCommand";

export type PluginBoardRewardResolvedCommand = PluginBoardRewardCommand | JsonValue;
