// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBoardRewardResolvedCommand } from "./PluginBoardRewardResolvedCommand";

export type PluginBoardRewardPreviewResponse = { plugin: string, mode: string, grant_enabled: boolean, reward: PluginBoardRewardResolvedCommand, };
