// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginPremiumPushStatusResponse = { plugin: string, status: string, license_required_for: Array<string>, };
