// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointExpireResult = { base_date: string, expired_count: number, synced_members: number, };
