// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointItem = { po_id: number, mb_id: string, po_point: number, po_datetime: string, po_content: string, po_use_point: number, po_expired: number, po_expire_date: string, po_mb_point: number, po_rel_table: string, po_rel_id: string, po_rel_action: string, };
