// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { PointDeleteResult } from "./PointDeleteResult";

export type PointDeleteResponse = { data: PointDeleteResult, meta: Meta, };
