// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";
import type { PollSummary } from "./PollSummary";

export type PollListResponse = { data: Array<PollSummary>, pagination: Pagination, meta: Meta, };
