// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PollSummary = { po_id: number, po_subject: string, po_date: string, po_level: number, po_point: number, po_use: number, };
