// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollNoInput } from "./PollNoInput";

export type PollVoteRequest = { poll_no?: PollNoInput, gb_poll?: PollNoInput, po_etc_text?: string, pc_idea?: string, };
