// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { PollPublicResult } from "./PollPublicResult";

export type PollResultResponse = { data: PollPublicResult, meta: Meta, };
