// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PollEtcItem = { pc_id: number, po_id: number, mb_id: string, pc_name: string, pc_idea: string, pc_datetime: string, };
