// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollChoice } from "./PollChoice";
import type { PollEtcItem } from "./PollEtcItem";

export type PollPublicResult = { po_id: number, po_subject: string, po_date: string, po_level: number, po_point: number, po_use: number, po_etc: string, total_votes: number, choices: Array<PollChoice>, etc_items?: Array<PollEtcItem>, };
