// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PollPublicResult } from "./PollPublicResult";

export type PollActiveResult = { active: boolean, can_vote: boolean, poll: PollPublicResult | null, };
