// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";
import type { Popup } from "./Popup";

export type PopupListResponse = { data: Array<Popup>, pagination: Pagination, meta: Meta, };
