// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";
import type { Post } from "./Post";

export type PostListResponse = { data: Array<Post>, pagination: Pagination, meta: Meta, };
