// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostScrapCreated = { ms_id: number, bo_table: string, wr_id: number, scraped: boolean, };
