// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostNoticeInput } from "./PostNoticeInput";

export type PostCreateRequest = { wr_subject: string, wr_content: string, ca_name?: string, wr_option?: string, wr_link1?: string, wr_link2?: string, is_notice?: PostNoticeInput, };
