// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostFile = { bo_table: string, wr_id: number, bf_no: number, bf_source: string, bf_file: string, bf_content: string, bf_fileurl: string, bf_thumburl: string, bf_storage: string, bf_download: number, bf_filesize: number, bf_width: number, bf_height: number, bf_type: number, bf_datetime: string, bf_file_mime: string, };
