// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { PostFile } from "./PostFile";

export type PostFileResponse = { data: PostFile, meta: Meta, };
