// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { PostVoteResult } from "./PostVoteResult";

export type PostVoteResponse = { data: PostVoteResult, meta: Meta, };
