// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostReplyCreated = { wr_id: number, bo_table: string, parent_wr_id: number, };
