// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostReplyRequest = { wr_subject: string, wr_content: string, wr_option?: string, };
