// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VisitDeleteResult = { deleted_rows: number, before: string | null, date_from: string | null, date_to: string | null, ip: string | null, };
