// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VisitLogItem = { vi_id?: number, vi_ip?: string, vi_date?: string, vi_time?: string, vi_referer?: string, vi_agent?: string, vi_browser?: string, vi_os?: string, vi_device?: string, };
