<?php

declare(strict_types=1);

namespace Api\Admin\Config\Repository;

final class AdminConfigUpdateBuilder
{
    public const UPDATABLE_FIELDS = [
        'cf_title',
        'cf_admin',
        'cf_admin_email',
        'cf_admin_email_name',
        'cf_add_script',
        'cf_use_email_certify',
        'cf_email_use',
        'cf_email_mb_member',
        'cf_email_mb_super_admin',
        'cf_email_po_super_admin',
        'cf_email_wr_board_admin',
        'cf_email_wr_comment_all',
        'cf_email_wr_group_admin',
        'cf_email_wr_super_admin',
        'cf_email_wr_write',
        'cf_use_homepage',
        'cf_req_homepage',
        'cf_use_tel',
        'cf_req_tel',
        'cf_use_hp',
        'cf_req_hp',
        'cf_use_addr',
        'cf_req_addr',
        'cf_cert_use',
        'cf_cert_find',
        'cf_cert_simple',
        'cf_cert_use_seed',
        'cf_cert_ipin',
        'cf_cert_hp',
        'cf_cert_kcb_cd',
        'cf_cert_kcp_cd',
        'cf_cert_kcp_enckey',
        'cf_cert_kg_cd',
        'cf_cert_kg_mid',
        'cf_cert_limit',
        'cf_cert_req',
        'cf_register_level',
        'cf_register_point',
        'cf_login_point',
        'cf_login_minutes',
        'cf_use_point',
        'cf_write_point',
        'cf_comment_point',
        'cf_download_point',
        'cf_read_point',
        'cf_recommend_point',
        'cf_memo_send_point',
        'cf_cut_name',
        'cf_nick_modify',
        'cf_leave_day',
        'cf_new_skin',
        'cf_new_rows',
        'cf_search_skin',
        'cf_connect_skin',
        'cf_faq_skin',
        'cf_editor',
        'cf_member_skin',
        'cf_mobile_member_skin',
        'cf_page_rows',
        'cf_write_pages',
        'cf_mobile_page_rows',
        'cf_mobile_pages',
        'cf_use_copy_log',
        'cf_captcha',
        'cf_captcha_mp3',
        'cf_recaptcha_site_key',
        'cf_recaptcha_secret_key',
        'cf_syndi_token',
        'cf_syndi_except',
        'cf_stipulation',
        'cf_privacy',
        'cf_prohibit_id',
        'cf_prohibit_email',
        'cf_analytics',
        'cf_add_meta',
        'cf_filter',
        'cf_open_modify',
        'cf_possible_ip',
        'cf_intercept_ip',
        'cf_bbs_rewrite',
        'cf_search_part',
        'cf_formmail_is_member',
        'cf_link_target',
        'cf_1_subj',
        'cf_2_subj',
        'cf_3_subj',
        'cf_4_subj',
        'cf_5_subj',
        'cf_6_subj',
        'cf_7_subj',
        'cf_8_subj',
        'cf_9_subj',
        'cf_10_subj',
        'cf_1',
        'cf_2',
        'cf_3',
        'cf_4',
        'cf_5',
        'cf_6',
        'cf_7',
        'cf_8',
        'cf_9',
        'cf_10',
        'cf_point_term',
        'cf_delay_sec',
        'cf_new_del',
        'cf_memo_del',
        'cf_visit_del',
        'cf_popular_del',
        'cf_image_extension',
        'cf_flash_extension',
        'cf_movie_extension',
        'cf_social_login_use',
        'cf_facebook_appid',
        'cf_facebook_secret',
        'cf_twitter_key',
        'cf_twitter_secret',
        'cf_googl_shorturl_apikey',
        'cf_google_clientid',
        'cf_google_secret',
        'cf_kakao_rest_key',
        'cf_kakao_client_secret',
        'cf_kakao_js_apikey',
        'cf_naver_clientid',
        'cf_naver_secret',
        'cf_payco_clientid',
        'cf_payco_secret',
        'cf_social_servicelist',
        'cf_icode_server_ip',
        'cf_icode_id',
        'cf_icode_pw',
        'cf_icode_server_port',
        'cf_icode_token_key',
        'cf_sms_use',
        'cf_sms_type',
        'cf_use_member_icon',
        'cf_icon_level',
        'cf_member_icon_width',
        'cf_member_icon_height',
        'cf_member_icon_size',
        'cf_member_img_width',
        'cf_member_img_height',
        'cf_member_img_size',
        'cf_use_profile',
        'cf_req_profile',
        'cf_use_signature',
        'cf_req_signature',
        'cf_use_recommend',
        'cf_use_promotion',
        'cf_mobile_new_skin',
        'cf_mobile_search_skin',
        'cf_mobile_connect_skin',
        'cf_mobile_faq_skin',
    ];

    /**
     * @param array<string, mixed> $payload
     * @return array{sets:list<string>, params:array<string, mixed>}
     */
    public function build(array $payload): array
    {
        $sets = [];
        $params = [];

        foreach (self::UPDATABLE_FIELDS as $field) {
            if (!array_key_exists($field, $payload)) {
                continue;
            }

            $param = 'u_' . $field;
            $sets[] = "{$field} = :{$param}";
            $params[$param] = $payload[$field];
        }

        return [
            'sets' => $sets,
            'params' => $params,
        ];
    }
}
