export const contentFaqSystemApiTargetsByCommand: Readonly<
  Record<string, string>
> = {
  "cmd_admin_dashboard_get": "/admin/dashboard",
  "cmd_admin_config_get": "/admin/config",
  "cmd_admin_config_update": "/admin/config",
  "cmd_admin_schema_get_catalog": "/admin/schema",
  "cmd_admin_schema_get": "/admin/schema/{domain}",
  "cmd_admin_content_get_list": "/admin/contents",
  "cmd_admin_content_create": "/admin/contents",
  "cmd_admin_content_get": "/admin/contents/{co_id}",
  "cmd_admin_content_update": "/admin/contents/{co_id}",
  "cmd_admin_content_delete": "/admin/contents/{co_id}",
  "cmd_admin_faq_master_get_list": "/admin/faq-masters",
  "cmd_admin_faq_master_create": "/admin/faq-masters",
  "cmd_admin_faq_master_get": "/admin/faq-masters/{fm_id}",
  "cmd_admin_faq_master_update": "/admin/faq-masters/{fm_id}",
  "cmd_admin_faq_master_delete": "/admin/faq-masters/{fm_id}",
  "cmd_admin_faq_master_header_image_upload": "/admin/faq-masters/{fm_id}/header-image",
  "cmd_admin_faq_master_header_image_delete": "/admin/faq-masters/{fm_id}/header-image",
  "cmd_admin_faq_master_footer_image_upload": "/admin/faq-masters/{fm_id}/footer-image",
  "cmd_admin_faq_master_footer_image_delete": "/admin/faq-masters/{fm_id}/footer-image",
  "cmd_admin_faq_get_list": "/admin/faqs",
  "cmd_admin_faq_create": "/admin/faqs",
  "cmd_admin_faq_get": "/admin/faqs/{fa_id}",
  "cmd_admin_faq_update": "/admin/faqs/{fa_id}",
  "cmd_admin_faq_delete": "/admin/faqs/{fa_id}",
  "cmd_admin_write_count_stats_get": "/admin/write-count/stats",
  "cmd_admin_phpinfo_get": "/admin/system/phpinfo",
  "cmd_admin_browscap_status_get": "/admin/system/browscap",
  "cmd_admin_browscap_update": "/admin/system/browscap/update",
  "cmd_admin_browscap_convert": "/admin/system/browscap/convert",
  "cmd_admin_visit_stats_get": "/admin/visits/stats",
  "cmd_admin_visit_search": "/admin/visits/search",
  "cmd_admin_visit_delete": "/admin/visits",
};
