export const membersBoardsApiTargetsByCommand: Readonly<Record<string, string>> =
  {
    "cmd_admin_member_get_list": "/admin/members",
    "cmd_admin_member_export_excel": "/admin/members/excel",
    "cmd_admin_member_get": "/admin/members/{mb_id}",
    "cmd_admin_member_update_level": "/admin/members/{mb_id}/level",
    "cmd_admin_member_update": "/admin/members/{mb_id}",
    "cmd_admin_member_icon_upload": "/admin/members/{mb_id}/icon",
    "cmd_admin_member_icon_delete": "/admin/members/{mb_id}/icon",
    "cmd_admin_member_image_upload": "/admin/members/{mb_id}/image",
    "cmd_admin_member_image_delete": "/admin/members/{mb_id}/image",
    "cmd_admin_member_delete": "/admin/members/{mb_id}",
    "cmd_admin_board_group_get_list": "/admin/board-groups",
    "cmd_admin_board_group_create": "/admin/board-groups",
    "cmd_admin_board_group_get": "/admin/board-groups/{gr_id}",
    "cmd_admin_board_group_update": "/admin/board-groups/{gr_id}",
    "cmd_admin_board_group_patch": "/admin/board-groups/{gr_id}",
    "cmd_admin_board_group_delete": "/admin/board-groups/{gr_id}",
    "cmd_admin_board_group_members_get": "/admin/board-groups/{gr_id}/members",
    "cmd_admin_board_group_member_add": "/admin/board-groups/{gr_id}/members",
    "cmd_admin_board_group_member_delete":
      "/admin/board-groups/{gr_id}/members/{mb_id}",
    "cmd_admin_group_legacy_get_list": "/admin/groups",
    "cmd_admin_group_legacy_create": "/admin/groups",
    "cmd_admin_group_legacy_get": "/admin/groups/{gr_id}",
    "cmd_admin_group_legacy_update": "/admin/groups/{gr_id}",
    "cmd_admin_group_legacy_delete": "/admin/groups/{gr_id}",
    "cmd_admin_group_legacy_members_get": "/admin/groups/{gr_id}/members",
    "cmd_admin_group_legacy_member_add": "/admin/groups/{gr_id}/members",
    "cmd_admin_group_legacy_member_delete":
      "/admin/groups/{gr_id}/members/{mb_id}",
    "cmd_admin_board_get_list": "/admin/boards",
    "cmd_admin_board_get": "/admin/boards/{bo_table}",
    "cmd_admin_board_create": "/admin/boards",
    "cmd_admin_board_update": "/admin/boards/{bo_table}",
    "cmd_admin_board_delete": "/admin/boards/{bo_table}",
    "cmd_admin_board_copy": "/admin/boards/{bo_table}/copy",
    "cmd_admin_board_new_posts_delete": "/admin/boards/new-posts",
  };
