import { describe, expect, it } from "vitest";
import {
  buildAdminMemberUpdateInput,
  emptyAdminMemberFormValues,
  toAdminMemberFormValues,
} from "./admin-members-form";
import type { AdminMemberDetail } from "../../types/AdminMemberDetail";

const baselineMember: AdminMemberDetail = {
  mb_id: "neojins",
  mb_1: "alpha",
  mb_2: null,
  mb_3: null,
  mb_4: null,
  mb_5: null,
  mb_6: null,
  mb_7: null,
  mb_8: null,
  mb_9: null,
  mb_10: "omega",
  mb_name: "Neo Jins",
  mb_nick: "neo",
  mb_email: "neo@example.com",
  mb_level: 9,
  mb_point: 1200,
  mb_mailling: 1,
  mb_sms: 0,
  mb_marketing_agree: 1,
  mb_thirdparty_agree: 0,
  mb_agree_log: null,
  mb_homepage: "https://example.com",
  mb_hp: "01012345678",
  mb_tel: "0212345678",
  mb_zip: "12345",
  mb_addr1: "Seoul",
  mb_addr2: "Gangnam",
  mb_addr3: "Tower",
  mb_addr_jibeon: "역삼동",
  mb_memo: "메모",
  mb_profile: "프로필",
  mb_signature: "서명",
  mb_adult: 1,
  mb_certify: "simple",
  mb_open: 1,
  mb_datetime: null,
  mb_today_login: null,
  mb_leave_date: null,
  mb_intercept_date: "",
};

describe("admin-members-form", () => {
  it("maps member detail into form values", () => {
    expect(toAdminMemberFormValues(baselineMember)).toEqual({
      mb_1: "alpha",
      mb_2: "",
      mb_3: "",
      mb_4: "",
      mb_5: "",
      mb_6: "",
      mb_7: "",
      mb_8: "",
      mb_9: "",
      mb_10: "omega",
      mb_name: "Neo Jins",
      mb_nick: "neo",
      mb_email: "neo@example.com",
      mb_homepage: "https://example.com",
      mb_hp: "01012345678",
      mb_tel: "0212345678",
      mb_zip: "12345",
      mb_addr1: "Seoul",
      mb_addr2: "Gangnam",
      mb_addr3: "Tower",
      mb_addr_jibeon: "역삼동",
      mb_memo: "메모",
      mb_profile: "프로필",
      mb_signature: "서명",
      mb_password: "",
      mb_certify: "simple",
      mb_leave_date: "",
      mb_intercept_date: "",
      mb_mailling: true,
      mb_sms: false,
      mb_marketing_agree: true,
      mb_thirdparty_agree: false,
      mb_adult: true,
      mb_open: true,
    });
  });

  it("returns null when no fields changed", () => {
    expect(
      buildAdminMemberUpdateInput(
        baselineMember,
        toAdminMemberFormValues(baselineMember),
      ),
    ).toBeNull();
  });

  it("builds sparse payload for changed fields only", () => {
    const input = buildAdminMemberUpdateInput(baselineMember, {
      ...emptyAdminMemberFormValues,
      mb_1: "beta",
      mb_10: "omega-2",
      mb_name: "Neo Jins",
      mb_nick: "neo-master",
      mb_email: "neo@example.com",
      mb_homepage: " https://example.org ",
      mb_hp: "01099998888",
      mb_tel: "",
      mb_zip: "54321",
      mb_addr1: "Busan",
      mb_addr2: "",
      mb_addr3: "센터",
      mb_addr_jibeon: "",
      mb_memo: " 새 메모 ",
      mb_profile: "",
      mb_signature: " 새 서명 ",
      mb_password: "secret123!",
      mb_certify: "hp",
      mb_leave_date: "20260308",
      mb_intercept_date: "20260307",
      mb_mailling: false,
      mb_sms: true,
      mb_marketing_agree: true,
      mb_thirdparty_agree: true,
      mb_adult: false,
      mb_open: false,
    });

    expect(input).toEqual({
      mb_id: "neojins",
      mb_1: "beta",
      mb_2: null,
      mb_3: null,
      mb_4: null,
      mb_5: null,
      mb_6: null,
      mb_7: null,
      mb_8: null,
      mb_9: null,
      mb_10: "omega-2",
      mb_name: null,
      mb_nick: "neo-master",
      mb_email: null,
      mb_homepage: "https://example.org",
      mb_hp: "01099998888",
      mb_tel: "",
      mb_zip: "54321",
      mb_addr1: "Busan",
      mb_addr2: "",
      mb_addr3: "센터",
      mb_addr_jibeon: "",
      mb_memo: "새 메모",
      mb_profile: "",
      mb_signature: "새 서명",
      mb_password: "secret123!",
      mb_certify: "hp",
      mb_leave_date: "20260308",
      mb_intercept_date: "20260307",
      mb_mailling: 0,
      mb_sms: 1,
      mb_marketing_agree: null,
      mb_thirdparty_agree: 1,
      mb_adult: 0,
      mb_open: 0,
    });
  });
});
