// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplateItem } from "./AdminSmsTemplateItem";
import type { Pagination } from "./Pagination";

export type AdminSmsTemplateListResponse = { templates: Array<AdminSmsTemplateItem>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
