// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminBrowscapConvertResult } from "./AdminBrowscapConvertResult";

export type AdminBrowscapConvertResponse = { result: AdminBrowscapConvertResult, request_id: string, correlation_id: string, server_request_id: string | null, };
