// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBoardGroupUpdateInput = { gr_id: string, gr_subject: string, gr_admin: string | null, gr_device: string | null, gr_use_access: number | null, };
