// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsBatchResendInput = { wr_no: number, wr_renum: number | null, booking_at: string | null, };
