// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactExportItem } from "./AdminSmsContactExportItem";

export type AdminSmsContactExportResponse = { items: Array<AdminSmsContactExportItem>, total: number, bg_no: number | null, include_no_phone: boolean, with_hyphen: boolean, request_id: string, correlation_id: string, server_request_id: string | null, };
