// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBoard = { bo_table: string, bo_subject: string | null, gr_id: string | null, bo_read_level: number | null, bo_write_level: number | null, bo_comment_level: number | null, bo_download_level: number | null, bo_use_category: number | null, bo_category_list: string | null, bo_count_write: number | null, bo_count_comment: number | null, bo_use_secret: number | null, bo_upload_count: number | null, bo_upload_size: number | null, extra: { [key in string]: string }, };
