// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMemberMediaResult = { mb_id: string, storage: string, relative_path: string | null, url: string | null, size: number | null, width: number | null, height: number | null, mime: string | null, deleted: boolean | null, };
