// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminThemeConfigUpdateInput = { cf_theme: string | null, cf_mobile_theme: string | null, };
