// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminReportUpdateInput = { report_id: number, status: string, admin_memo: string | null, };
