// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminVisitStatItem } from "./AdminVisitStatItem";
import type { AdminVisitStatsSummary } from "./AdminVisitStatsSummary";

export type AdminVisitStatsResponse = { type: string, summary: AdminVisitStatsSummary, items: Array<AdminVisitStatItem>, request_id: string, correlation_id: string, server_request_id: string | null, };
