// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateListQuery = { page: number, per_page: number, fg_no: number | null, search_field: string | null, search: string | null, };
