// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminFieldSchema } from "./AdminFieldSchema";

export type AdminSchemaSection = { key: string, label: string, order: number, description: string | null, fields: Array<AdminFieldSchema>, };
