// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSchemaDomainSummary } from "./AdminSchemaDomainSummary";

export type AdminSchemaCatalog = { items: Array<AdminSchemaDomainSummary>, total: number, };
