// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateUpdateInput = { fo_no: number, fg_no: number | null, fo_name: string | null, fo_content: string | null, };
