// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactItem } from "./AdminSmsContactItem";
import type { AdminSmsContactSummary } from "./AdminSmsContactSummary";
import type { Pagination } from "./Pagination";

export type AdminSmsContactListResponse = { contacts: Array<AdminSmsContactItem>, pagination: Pagination, summary: AdminSmsContactSummary, request_id: string, correlation_id: string, server_request_id: string | null, };
