// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactListQuery = { page: number, per_page: number, bg_no: number | null, search_field: string | null, search: string | null, with_phone_only: boolean | null, };
