// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminFieldSchema } from "./AdminFieldSchema";
import type { AdminSchemaLayout } from "./AdminSchemaLayout";
import type { AdminSchemaSection } from "./AdminSchemaSection";

export type AdminSchemaDetail = { domain: string, title: string, legacy_form: string, field_count: number, section_count: number, generated_at: string, layout: AdminSchemaLayout | null, sections: Array<AdminSchemaSection>, fields_by_name: { [key in string]: AdminFieldSchema }, };
