// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPopularItem } from "./AdminPopularItem";
import type { Pagination } from "./Pagination";

export type AdminPopularListResponse = { populars: Array<AdminPopularItem>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
