// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPointSummary = { mb_id: string | null, total_point: number, total_rows: number, };
