// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBoardListQuery = { page: number, per_page: number, gr_id: string | null, search: string | null, };
