// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminFieldDefaultValue } from "./AdminFieldDefaultValue";
import type { AdminFieldOption } from "./AdminFieldOption";
import type { AdminFieldOptionSource } from "./AdminFieldOptionSource";

export type AdminFieldSchema = { name: string, label: string, input_type: string, data_type: string, required: boolean, create_only: boolean, readonly_on_update: boolean, description: string | null, default_value: AdminFieldDefaultValue | null, options: Array<AdminFieldOption>, option_source?: AdminFieldOptionSource | null, };
