// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMenu } from "./AdminMenu";
import type { Pagination } from "./Pagination";

export type AdminMenuListResponse = { menus: Array<AdminMenu>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
