// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLayoutWidgetUpdateInput = { page_id: string, widget_id: string, type: string | null, title: string | null, order: number | null, config_json: string | null, style_json: string | null, };
