// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailRecipientQuery = { page: number, per_page: number, search: string | null, level_min: number | null, level_max: number | null, gr_id: string | null, member_id_from: string | null, member_id_to: string | null, email_contains: string | null, mailling_only: boolean, };
