// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminVisitLogItem = { vi_id: number, vi_ip: string | null, vi_date: string | null, vi_time: string | null, vi_referer: string | null, vi_agent: string | null, vi_browser: string | null, vi_os: string | null, vi_device: string | null, };
