// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateItem = { fo_no: number, fg_no: number, fg_member: number, fg_name: string | null, fo_name: string, fo_content: string, fo_datetime: string | null, };
