// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMaintenanceResult = { task: string, status: string, directory: string, deleted_count: number, deleted_paths: Array<string>, message: string | null, social_log_deleted_count: number | null, };
