// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMenuCreateInput = { me_code: string, me_name: string, me_link: string, me_target: string | null, me_order: number | null, me_use: number | null, me_mobile_use: number | null, };
