// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPopularListQuery = { page: number, per_page: number, date_from: string | null, date_to: string | null, };
