// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMemberDetail } from "./AdminMemberDetail";

export type AdminMemberDetailResponse = { member: AdminMemberDetail, request_id: string, correlation_id: string, server_request_id: string | null, };
