// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardRecentPoint = { po_id: number | null, mb_id: string | null, mb_name: string | null, mb_nick: string | null, po_datetime: string | null, po_content: string | null, po_point: number | null, po_mb_point: number | null, po_rel_table: string | null, po_rel_id: string | null, po_rel_action: string | null, };
