// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateBatchResult = { action: string, affected: number, target_fg_no: number | null, };
