// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPopularResetResult = { deleted_rows: number, date_from: string | null, date_to: string | null, };
