// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsDeliveryItem } from "./AdminSmsDeliveryItem";
import type { Pagination } from "./Pagination";

export type AdminSmsDeliveryListResponse = { deliveries: Array<AdminSmsDeliveryItem>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
