// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemMailRecipient = { mb_id: string, mb_name: string, mb_nick: string, mb_email: string, mb_level: number, mb_mailling: number, mb_today_login: string, };
