// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardRecentMember = { mb_id: string | null, mb_name: string | null, mb_nick: string | null, mb_level: number | null, mb_point: number | null, mb_datetime: string | null, mb_mailling: boolean | null, mb_open: boolean | null, email_certified: boolean | null, intercepted: boolean | null, group_count: number | null, };
