// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardRecentPost = { bn_id: number | null, gr_id: string | null, gr_subject: string | null, bo_table: string | null, bo_subject: string | null, wr_id: number | null, wr_parent: number | null, view_type: string | null, wr_subject: string | null, parent_wr_subject: string | null, wr_name: string | null, wr_datetime: string | null, post_mb_id: string | null, post_exists: boolean | null, };
