// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminFaqImage } from "./AdminFaqImage";

export type AdminFaqMasterDetail = { fm_id: number, fm_subject: string, fm_head_html: string, fm_tail_html: string, fm_mobile_head_html: string, fm_mobile_tail_html: string, fm_order: number, faq_count: number, header_image: AdminFaqImage, footer_image: AdminFaqImage, };
