// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminReportListQuery = { page: number, per_page: number, status: string | null, target_type: string | null, };
