// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsRetryBatchItem = { wr_no: number, wr_renum: number, wr_total: number, wr_success: number, wr_failure: number, wr_datetime: string | null, };
