// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPointActionInput = { mb_id: string, point: number, po_content: string | null, };
