// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsManualTarget } from "./AdminSmsManualTarget";

export type AdminSmsSendInput = { message: string | null, template_id: number | null, group_ids: Array<number>, contact_ids: Array<number>, member_levels: Array<number>, manual_targets: Array<AdminSmsManualTarget>, booking_at: string | null, wr_reply: string | null, };
