// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemMailRecipient } from "./AdminSystemMailRecipient";
import type { ApiTraceMeta } from "./ApiTraceMeta";
import type { Pagination } from "./Pagination";

export type AdminSystemMailRecipientListResponse = { data: Array<AdminSystemMailRecipient>, pagination: Pagination, meta: ApiTraceMeta, };
