// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMemberListItem } from "./AdminMemberListItem";
import type { Pagination } from "./Pagination";

export type AdminMemberListResponse = { members: Array<AdminMemberListItem>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
