// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactUpdateInput = { bk_no: number, bg_no: number | null, bk_name: string | null, bk_hp: string | null, bk_receipt: number | null, bk_memo: string | null, };
