// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminContentCreateInput = { co_id: string, co_subject: string, co_html: number, co_content: string, co_mobile_content: string | null, co_include_head: string | null, co_include_tail: string | null, co_tag_filter_use: number | null, co_skin: string | null, co_mobile_skin: string | null, };
