// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMenuUpdateInput = { me_id: number, me_code: string | null, me_name: string | null, me_link: string | null, me_target: string | null, me_order: number | null, me_use: number | null, me_mobile_use: number | null, };
