// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsMemberSyncSummary = { total_members: number, leave_members: number, phone_empty: number, phone_valid: number, phone_invalid: number, receipt_enabled: number, receipt_disabled: number, };
