// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSchemaDomainSummary = { domain: string, title: string, legacy_form: string, field_count: number, section_count: number, generated_at: string, };
