// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsImportContactRow } from "./AdminSmsImportContactRow";

export type AdminSmsContactImportInput = { bg_no: number, dry_run: boolean, bytes: Array<number> | null, file_name: string | null, mime_type: string | null, contacts: Array<AdminSmsImportContactRow> | null, };
