// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminWriteCountStatsQuery = { period: string | null, date_from: string | null, date_to: string | null, bo_table: string | null, };
