// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorGuide } from "./ErrorGuide";

export type AppErrorPayload = { code: string, message: string, guide: ErrorGuide | null, request_id: string, correlation_id: string, server_request_id: string | null, status: number | null, target: string | null, detail: string | null, error_category: string, fault_domain: string, owner: string, retryable: boolean, user_actionable: boolean, };
