// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugRuntimeInfo = { active_site_id: string | null, active_site_name: string | null, api_base_url: string | null, database_path: string, debug_build: boolean, debug_overlay: boolean, session_storage: string, session_storage_target: string, log_file_path: string, request_id: string, correlation_id: string, server_request_id: string | null, };
