// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugDevBootstrapResult = { master_lock_configured: boolean, master_lock_unlocked: boolean, site_id: string | null, site_name: string | null, site_login_mb_id: string | null, site_login_authenticated: boolean, created_ssh_profile_count: number, updated_ssh_profile_count: number, request_id: string, correlation_id: string, server_request_id: string | null, };
