// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiTraceMeta } from "./ApiTraceMeta";

export type HealthResponse = { status: string, version: string, timestamp: bigint, meta: ApiTraceMeta, };
