// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MasterLockStatus = { is_configured: boolean, is_unlocked: boolean, passkey_enabled: boolean, totp_enabled: boolean, requires_totp: boolean, unlock_retry_after_seconds: bigint | null, unlock_locked_until_epoch: bigint | null, request_id: string, correlation_id: string, server_request_id: string | null, };
