// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemberProfile = { mb_id: string, mb_name: string | null, mb_nick: string | null, mb_email: string | null, mb_level: number | null, mb_point: number | null, };
