// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SecuritySettings = { fast_unlock_available: boolean, fast_unlock_enabled: boolean, idle_timeout_minutes: number | null, totp_enabled: boolean, request_id: string, correlation_id: string, server_request_id: string | null, };
