// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityStepUpAuthInput } from "./SecurityStepUpAuthInput";

export type SecurityIdleTimeoutUpdateInput = { idle_timeout_minutes: number | null, auth: SecurityStepUpAuthInput, };
