// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpMoveInput = { site_id: string, source_path: string, destination_path: string, };
