// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpReadFileResponse = { site_id: string, requested_path: string, resolved_path: string, content: string, byte_length: number, truncated: boolean, utf8_lossy: boolean, request_id: string, correlation_id: string, server_request_id: string | null, };
