// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpChmodInput = { site_id: string, path: string, permissions_octal: string, };
