// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpEntryKind } from "./SftpEntryKind";
import type { SftpTransferDirection } from "./SftpTransferDirection";
import type { SftpTransferItemStatus } from "./SftpTransferItemStatus";

export type SftpTransferQueueItem = { id: string, site_id: string, direction: SftpTransferDirection, source_path: string, destination_path: string, source_kind: SftpEntryKind | null, recursive: boolean, label: string, status: SftpTransferItemStatus, attempt_count: number, copied_bytes: bigint | null, error_message: string | null, queued_at_epoch_ms: bigint, completed_at_epoch_ms: bigint | null, };
