// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpDownloadResponse = { site_id: string, requested_path: string, resolved_path: string, destination_path: string, copied_bytes: bigint, request_id: string, correlation_id: string, server_request_id: string | null, };
