// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpDirectoryEntry } from "./SftpDirectoryEntry";

export type SftpDirectoryListResponse = { site_id: string, requested_path: string, resolved_path: string, parent_path: string | null, entries: Array<SftpDirectoryEntry>, request_id: string, correlation_id: string, server_request_id: string | null, };
