// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpEntryKind } from "./SftpEntryKind";

export type SftpMoveResponse = { site_id: string, requested_source_path: string, source_resolved_path: string, requested_destination_path: string, resolved_destination_path: string, kind: SftpEntryKind, request_id: string, correlation_id: string, server_request_id: string | null, };
