// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpTransferQueueItem } from "./SftpTransferQueueItem";

export type SftpTransferQueueSnapshot = { site_id: string, items: Array<SftpTransferQueueItem>, active_count: number, queued_count: number, paused_count: number, cancelled_count: number, failed_count: number, concurrency_limit: number, };
