// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpEntryKind } from "./SftpEntryKind";
import type { SftpTransferDirection } from "./SftpTransferDirection";

export type SftpTransferEnqueueItemInput = { direction: SftpTransferDirection, source_path: string, destination_path: string, source_kind: SftpEntryKind | null, recursive: boolean, label: string | null, };
