// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpPathMetadata } from "./SftpPathMetadata";

export type SftpDirectoryEntry = { name: string, path: string, metadata: SftpPathMetadata, };
