// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SftpWriteFileResponse = { site_id: string, requested_path: string, resolved_path: string, byte_length: number, request_id: string, correlation_id: string, server_request_id: string | null, };
