// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SiteBackupExportResult = { path: string, site_count: number, copied_bytes: bigint, request_id: string, correlation_id: string, server_request_id: string | null, };
