// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteCatalogEntry } from "./SiteCatalogEntry";

export type SiteCatalog = { sites: Array<SiteCatalogEntry>, active_site_id: string | null, needs_onboarding: boolean, request_id: string, correlation_id: string, server_request_id: string | null, };
