// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SiteUpdateInput = { site_id: string, name: string, api_base_url: string, is_default: boolean, };
