// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshProfile } from "./SshProfile";

export type SshProfileListResponse = { site_id: string, profiles: Array<SshProfile>, request_id: string, correlation_id: string, server_request_id: string | null, };
