// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAuthType } from "./SshAuthType";

export type SshProfileUpdateInput = { site_id: string, ssh_profile_id: string, name: string, host: string, port: number, username: string, auth_type: SshAuthType, key_path: string | null, password: string | null, key_passphrase: string | null, clear_password: boolean, clear_key_passphrase: boolean, };
