// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshTerminalBridgeConnectionResponse = { site_id: string, websocket_url: string, token: string, request_id: string, correlation_id: string, server_request_id: string | null, };
