export const localApiTargetsByCommand: Readonly<Record<string, string>> = {
  "cmd_auth_status": "/members/me",
  "cmd_master_lock_status": "local://master-lock/status",
  "cmd_master_lock_setup": "local://master-lock/setup",
  "cmd_master_lock_unlock": "local://master-lock/unlock",
  "cmd_master_lock_unlock_fast": "local://master-lock/fast-unlock",
  "cmd_master_lock_verify_totp": "local://master-lock/unlock-totp",
  "cmd_master_lock_lock": "local://master-lock/lock",
  "cmd_security_settings_get": "local://security/settings",
  "cmd_security_fast_unlock_status": "local://security/fast-unlock/status",
  "cmd_security_enable_fast_unlock": "local://security/fast-unlock/enable",
  "cmd_security_disable_fast_unlock": "local://security/fast-unlock/disable",
  "cmd_security_change_master_password": "local://security/master-password",
  "cmd_security_update_idle_timeout": "local://security/idle-timeout",
  "cmd_security_start_totp_enrollment": "local://security/totp/enrollment",
  "cmd_security_enable_totp": "local://security/totp/enable",
  "cmd_security_disable_totp": "local://security/totp/disable",
  "cmd_backup_export": "local://backup/export",
  "cmd_backup_import": "local://backup/import",
  "cmd_site_catalog_get": "local://sites/catalog",
  "cmd_site_health_check": "local://sites/health-check",
  "cmd_site_add": "local://sites",
  "cmd_site_update": "local://sites/{site_id}",
  "cmd_site_delete": "local://sites/{site_id}",
  "cmd_site_switch": "local://sites/{site_id}/switch",
  "cmd_site_activity_list": "local://sites/activity",
  "cmd_ssh_status": "local://sites/{site_id}/ssh-session",
  "cmd_ssh_connect": "local://sites/{site_id}/ssh-session",
  "cmd_ssh_disconnect": "local://sites/{site_id}/ssh-session",
  "cmd_ssh_host_verification_status":
    "local://sites/{site_id}/ssh-host-verification",
  "cmd_ssh_host_verification_trust":
    "local://sites/{site_id}/ssh-host-verification/trust",
  "cmd_ssh_shell_open": "local://sites/{site_id}/ssh-shell",
  "cmd_ssh_terminal_bridge_connect": "local://sites/{site_id}/ssh-shell/bridge",
  "cmd_ssh_shell_write": "local://sites/{site_id}/ssh-shell",
  "cmd_ssh_shell_read": "local://sites/{site_id}/ssh-shell",
  "cmd_ssh_shell_close": "local://sites/{site_id}/ssh-shell",
  "cmd_ssh_shell_resize": "local://sites/{site_id}/ssh-shell/resize",
  "cmd_sftp_list_dir": "local://sites/{site_id}/sftp",
  "cmd_sftp_stat": "local://sites/{site_id}/sftp/stat",
  "cmd_sftp_read_file": "local://sites/{site_id}/sftp/file",
  "cmd_sftp_download": "local://sites/{site_id}/sftp/download",
  "cmd_sftp_upload": "local://sites/{site_id}/sftp/upload",
  "cmd_sftp_copy": "local://sites/{site_id}/sftp/copy",
  "cmd_sftp_move": "local://sites/{site_id}/sftp/move",
  "cmd_sftp_chmod": "local://sites/{site_id}/sftp/chmod",
  "cmd_sftp_delete": "local://sites/{site_id}/sftp/delete",
  "cmd_sftp_mkdir": "local://sites/{site_id}/sftp/mkdir",
  "cmd_sftp_write_file": "local://sites/{site_id}/sftp/write",
  "cmd_sftp_transfer_snapshot": "local://sites/{site_id}/sftp/transfers",
  "cmd_sftp_transfer_enqueue": "local://sites/{site_id}/sftp/transfers/enqueue",
  "cmd_sftp_transfer_pause": "local://sites/{site_id}/sftp/transfers/{item_id}/pause",
  "cmd_sftp_transfer_retry": "local://sites/{site_id}/sftp/transfers/{item_id}/retry",
  "cmd_sftp_transfer_cancel": "local://sites/{site_id}/sftp/transfers/{item_id}/cancel",
  "cmd_sftp_transfer_set_concurrency": "local://sites/{site_id}/sftp/transfers/concurrency",
  "cmd_ssh_profile_list": "local://sites/{site_id}/ssh-profiles",
  "cmd_ssh_profile_add": "local://sites/{site_id}/ssh-profiles",
  "cmd_ssh_profile_update": "local://sites/{site_id}/ssh-profiles/{ssh_profile_id}",
  "cmd_ssh_profile_delete": "local://sites/{site_id}/ssh-profiles/{ssh_profile_id}",
  "cmd_auth_login": "/auth/login",
  "cmd_auth_logout": "/auth/logout",
  "cmd_auth_refresh": "/auth/refresh",
  "cmd_system_health": "/health",
  "cmd_member_me_get": "/members/me",
};
