export const smsDebugApiTargetsByCommand: Readonly<Record<string, string>> = {
  "cmd_admin_sms_config_get": "/admin/sms/config",
  "cmd_admin_sms_config_update": "/admin/sms/config",
  "cmd_admin_sms_member_sync": "/admin/sms/member-sync",
  "cmd_admin_sms_template_group_get_list": "/admin/sms/template-groups",
  "cmd_admin_sms_template_group_create": "/admin/sms/template-groups",
  "cmd_admin_sms_template_group_get": "/admin/sms/template-groups/{fg_no}",
  "cmd_admin_sms_template_group_update": "/admin/sms/template-groups/{fg_no}",
  "cmd_admin_sms_template_group_delete": "/admin/sms/template-groups/{fg_no}",
  "cmd_admin_sms_template_group_move": "/admin/sms/template-groups/{fg_no}/move",
  "cmd_admin_sms_template_group_clear":
    "/admin/sms/template-groups/{fg_no}/templates",
  "cmd_admin_sms_template_get_list": "/admin/sms/templates",
  "cmd_admin_sms_template_create": "/admin/sms/templates",
  "cmd_admin_sms_template_get": "/admin/sms/templates/{fo_no}",
  "cmd_admin_sms_template_update": "/admin/sms/templates/{fo_no}",
  "cmd_admin_sms_template_delete": "/admin/sms/templates/{fo_no}",
  "cmd_admin_sms_template_batch": "/admin/sms/templates/batch",
  "cmd_admin_sms_contact_group_get_list": "/admin/sms/contact-groups",
  "cmd_admin_sms_contact_group_create": "/admin/sms/contact-groups",
  "cmd_admin_sms_contact_group_get": "/admin/sms/contact-groups/{bg_no}",
  "cmd_admin_sms_contact_group_update": "/admin/sms/contact-groups/{bg_no}",
  "cmd_admin_sms_contact_group_delete": "/admin/sms/contact-groups/{bg_no}",
  "cmd_admin_sms_contact_group_move": "/admin/sms/contact-groups/{bg_no}/move",
  "cmd_admin_sms_contact_group_clear":
    "/admin/sms/contact-groups/{bg_no}/contacts",
  "cmd_admin_sms_contact_get_list": "/admin/sms/contacts",
  "cmd_admin_sms_contact_create": "/admin/sms/contacts",
  "cmd_admin_sms_contact_get": "/admin/sms/contacts/{bk_no}",
  "cmd_admin_sms_contact_update": "/admin/sms/contacts/{bk_no}",
  "cmd_admin_sms_contact_delete": "/admin/sms/contacts/{bk_no}",
  "cmd_admin_sms_contact_batch": "/admin/sms/contacts/batch",
  "cmd_admin_sms_contact_import": "/admin/sms/contacts/import",
  "cmd_admin_sms_contact_export": "/admin/sms/contacts/export",
  "cmd_admin_sms_message_batch_get_list": "/admin/sms/history/batches",
  "cmd_admin_sms_message_batch_get": "/admin/sms/history/batches/{wr_no}",
  "cmd_admin_sms_delivery_get_list": "/admin/sms/history/deliveries",
  "cmd_admin_sms_message_batch_resend_failures":
    "/admin/sms/history/batches/{wr_no}/resend-failures",
  "cmd_admin_sms_message_batch_resend_all":
    "/admin/sms/history/batches/{wr_no}/resend-all",
  "cmd_admin_sms_message_send": "/admin/sms/messages",
  "cmd_debug_runtime_info": "local://debug/runtime-info",
  "cmd_debug_dev_bootstrap_status": "local://debug/dev-bootstrap-status",
  "cmd_debug_dev_bootstrap_apply": "local://debug/dev-bootstrap-apply",
  "cmd_debug_log_tail": "local://debug/log-tail",
  "cmd_debug_open_devtools": "local://debug/devtools",
};
