[package]
name = "g5-fleet-admin-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
local-certification = ["g5-fleet-connector/local-certification"]

[dependencies]
axum.workspace = true
base64.workspace = true
g5-fleet-connector = { path = "../../crates/fleet-connector" }
g5-fleet-notify = { path = "../../crates/fleet-notify" }
g5-fleet-remote = { path = "../../crates/fleet-remote" }
g5-fleet-security = { path = "../../crates/fleet-security" }
g5-fleet-store = { path = "../../crates/fleet-store" }
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
async-trait.workspace = true
http-body-util.workspace = true
tower.workspace = true
