from __future__ import annotations

import importlib.util
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

SCRIPT_PATH = Path(__file__).resolve().parents[1] / "run_hotspot_audit.py"
sys.path.insert(0, str(SCRIPT_PATH.parent))
SPEC = importlib.util.spec_from_file_location("run_hotspot_audit", SCRIPT_PATH)
assert SPEC is not None and SPEC.loader is not None
MODULE = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = MODULE
SPEC.loader.exec_module(MODULE)


class HotspotAuditTest(unittest.TestCase):
    def test_all_workspace_rust_crates_are_relevant(self) -> None:
        self.assertTrue(
            MODULE.relevant_source_file("g5-admin-transport/src/request.rs")
        )
        self.assertTrue(
            MODULE.relevant_source_file("g5-admin-local-store/src/security.rs")
        )
        self.assertFalse(MODULE.relevant_source_file("specs/HISTORY.md"))

    def test_check_mode_is_available_for_non_mutating_ci(self) -> None:
        with patch.object(sys, "argv", ["run_hotspot_audit.py", "--check"]):
            args = MODULE.parse_args()

        self.assertTrue(args.check)

    def test_explicit_generated_marker_excludes_machine_output(self) -> None:
        with tempfile.TemporaryDirectory() as temporary_directory:
            generated = Path(temporary_directory) / "generated.rs"
            generated.write_text(
                "// @generated by contract generator; do not edit.\n" + "x\n" * 600,
                encoding="utf-8",
            )
            handwritten = Path(temporary_directory) / "handwritten.rs"
            handwritten.write_text("fn main() {}\n", encoding="utf-8")

            self.assertTrue(MODULE.generated_source_file(generated))
            self.assertFalse(MODULE.generated_source_file(handwritten))

    def test_workspace_unit_roots_include_extracted_crates(self) -> None:
        roots = MODULE.discover_unit_roots()

        self.assertIn("g5-admin-transport", roots)
        self.assertIn("g5-admin-api-client", roots)
        self.assertEqual(
            MODULE.ROOT / "g5-admin-transport/src",
            roots["g5-admin-transport"],
        )

    def test_warning_is_visible_without_blocking_the_fast_gate(self) -> None:
        self.assertEqual("warning", MODULE.derive_status(0, 1, 0))
        self.assertEqual("failed", MODULE.derive_status(1, 0, 0))


if __name__ == "__main__":
    unittest.main()
