// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailLastOption } from "./AdminMailLastOption";

export type AdminMailDetail = { ma_id: number, ma_subject: string, ma_content: string, ma_time: string, ma_ip: string, ma_last_option: string, last_option: AdminMailLastOption, preview_html: string, };
