// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactGroupMoveResult = { from_bg_no: number, target_bg_no: number, affected: number, };
