// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactGroup } from "./AdminSmsContactGroup";
import type { AdminSmsContactGroupListResponseMeta } from "./AdminSmsContactGroupListResponseMeta";

export type AdminSmsContactGroupListResponse = { data: Array<AdminSmsContactGroup>, meta: AdminSmsContactGroupListResponseMeta, };
