// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactImportItem } from "./AdminSmsContactImportItem";

export type AdminSmsContactImportJsonRequest = { bg_no?: number, upload_bg_no?: number, dry_run?: boolean, confirm?: boolean, contacts: Array<AdminSmsContactImportItem>, };
