// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminReportStats } from "./AdminReportStats";
import type { Meta } from "./Meta";

export type AdminReportStatsResponse = { data: AdminReportStats, meta: Meta, };
