// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateBatchRequest = { action: string, template_ids?: Array<number>, fo_no?: Array<number>, target_fg_no?: number, };
