// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemMailTemplate } from "./AdminSystemMailTemplate";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminSystemMailTemplateListResponse = { data: Array<AdminSystemMailTemplate>, pagination: Pagination, meta: Meta, };
