// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthMember } from "./AdminAuthMember";
import type { Meta } from "./Meta";

export type AdminAuthMemberResponse = { data: AdminAuthMember, meta: Meta, };
