// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactExportItem } from "./AdminSmsContactExportItem";
import type { AdminSmsContactExportResponseMeta } from "./AdminSmsContactExportResponseMeta";

export type AdminSmsContactExportResponse = { data: Array<AdminSmsContactExportItem>, meta: AdminSmsContactExportResponseMeta, };
