// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailTemplateRequest = { ma_subject?: string, ma_content?: string, subject?: string, content?: string, };
