// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsMemberSyncResult } from "./AdminSmsMemberSyncResult";
import type { Meta } from "./Meta";

export type AdminSmsMemberSyncResponse = { data: AdminSmsMemberSyncResult, meta: Meta, };
