// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminGroupMemberResult } from "./AdminGroupMemberResult";
import type { Meta } from "./Meta";

export type AdminGroupMemberResponse = { data: AdminGroupMemberResult, meta: Meta, };
