// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsManualTarget = { name?: string, phone?: string, bk_name?: string, bk_hp?: string, };
