// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminVisitDeleteRequest = { before?: string, date_from?: string, date_to?: string, ip?: string, };
