// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMemberUploadFile } from "./AdminMemberUploadFile";

export type AdminMemberIconUploadRequest = { file?: AdminMemberUploadFile, icon?: AdminMemberUploadFile, mb_icon?: AdminMemberUploadFile, };
