// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailLastOption = { mb_id1: number, mb_id1_from: string, mb_id1_to: string, mb_email: string, mb_mailling: number, mb_level_from: number, mb_level_to: number, gr_id: string, };
