// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLayoutSummary } from "./AdminLayoutSummary";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminLayoutListResponse = { data: Array<AdminLayoutSummary>, pagination: Pagination, meta: Meta, };
