// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemBrowscapConvertResult = { rows: number, total_pending_before: number, processed_count: number, remaining_count: number, completed: boolean, };
