// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminGroupMember = { gm_id: number, gr_id: string, mb_id: string, gm_datetime: string, mb_name: string | null, mb_nick: string | null, mb_level: number | null, mb_today_login: string | null, };
