// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemMailSendRecipient } from "./AdminSystemMailSendRecipient";

export type AdminSystemMailSendResult = { mail_log_id: number, target_count: number, sent_count: number, skipped_count: number, mail_enabled: boolean, dry_run: boolean, recipients: Array<AdminSystemMailSendRecipient>, };
