// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminGroupMember } from "./AdminGroupMember";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminGroupMemberListResponse = { data: Array<AdminGroupMember>, pagination: Pagination, meta: Meta, };
