// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthMember } from "./AdminAuthMember";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminAuthMemberListResponse = { data: Array<AdminAuthMember>, pagination: Pagination, meta: Meta, };
