// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemBrowscapStatus = { available: boolean, plugin_path: string, cache_directory: string, cache_file: string, cache_exists: boolean, php_version: string, pending_visit_count: number, updated?: boolean, cache_mtime?: string | null, };
