// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactListResponseMeta = { request_id?: string, correlation_id?: string, server_request_id?: string, server_time?: string, version?: string, error_code?: string, error_category?: string, fault_domain?: string, owner?: string, retryable?: boolean, user_actionable?: boolean, total_count: number, receipt_count: number, reject_count: number, member_count: number, non_member_count: number, last_synced_at: string | null, };
