// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailRecipient } from "./AdminMailRecipient";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminMailRecipientListResponse = { data: Array<AdminMailRecipient>, pagination: Pagination, meta: Meta, };
