// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContact } from "./AdminSmsContact";
import type { Meta } from "./Meta";

export type AdminSmsContactDetailResponse = { data: AdminSmsContact, meta: Meta, };
