// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemBrowscapStatus } from "./AdminSystemBrowscapStatus";
import type { Meta } from "./Meta";

export type AdminSystemBrowscapStatusResponse = { data: AdminSystemBrowscapStatus, meta: Meta, };
