// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardRecentPost = { bn_id?: number, gr_id?: string, gr_subject?: string, bo_table?: string, bo_subject?: string, wr_id?: number, wr_parent?: number, view_type?: string, wr_subject?: string, parent_wr_subject?: string, wr_name?: string, wr_datetime?: string, post_mb_id?: string, post_exists?: boolean, };
