// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLayoutSummary = { sl_id: number, sl_page_id: string, sl_title: string, sl_active: number, sl_datetime: string, sl_updated: string, };
