// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemPollCreateRequest = { po_subject: string, po_poll1: string, po_poll2: string, po_poll3?: string, po_poll4?: string, po_poll5?: string, po_poll6?: string, po_poll7?: string, po_poll8?: string, po_poll9?: string, po_etc?: string, po_level?: number, po_point?: number, po_use?: number, };
