// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminWriteCountStats } from "./AdminWriteCountStats";
import type { Meta } from "./Meta";

export type AdminWriteCountStatsResponse = { data: AdminWriteCountStats, meta: Meta, };
