// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplateGroupMoveResult } from "./AdminSmsTemplateGroupMoveResult";
import type { Meta } from "./Meta";

export type AdminSmsTemplateGroupMoveResponse = { data: AdminSmsTemplateGroupMoveResult, meta: Meta, };
