// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminNewPostsDeleteResult = { deleted: boolean, deleted_count: number, deleted_posts: number, deleted_comments: number, skipped: number, bn_ids: Array<number>, };
