// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailTemplate } from "./AdminMailTemplate";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminMailListResponse = { data: Array<AdminMailTemplate>, pagination: Pagination, meta: Meta, };
