// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPushSendResult = { requested_by: string, target_count: number, queued: number, failed: number, };
