// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailTestRequest = { ma_id?: number, to: string, subject?: string, content?: string, };
