// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemBrowscapConvertResult } from "./AdminSystemBrowscapConvertResult";
import type { Meta } from "./Meta";

export type AdminSystemBrowscapConvertResponse = { data: AdminSystemBrowscapConvertResult, meta: Meta, };
