// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsConfigUpdateRequest = { cf_sms_use?: string, cf_sms_type?: string, cf_icode_id?: string, cf_icode_pw?: string, cf_icode_server_ip?: string, cf_icode_server_port?: string, cf_icode_token_key?: string, cf_phone?: string, };
