// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateGroup = { fg_no: number, fg_name: string, fg_count: number, fg_member: number, is_virtual: boolean, };
