// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateCreateRequest = { fg_no?: number, fo_name: string, fo_content: string, };
