// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemMailSendRequest = { ma_id?: number, subject?: string, content?: string, mb_ids: Array<string>, mailling_only?: boolean, dry_run?: boolean, };
