// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplateGroup } from "./AdminSmsTemplateGroup";
import type { AdminSmsTemplateGroupListResponseMeta } from "./AdminSmsTemplateGroupListResponseMeta";

export type AdminSmsTemplateGroupListResponse = { data: Array<AdminSmsTemplateGroup>, meta: AdminSmsTemplateGroupListResponseMeta, };
