// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactImportFile } from "./AdminSmsContactImportFile";

export type AdminSmsContactImportMultipartRequest = { bg_no?: number, upload_bg_no?: number, dry_run?: boolean, confirm?: boolean, file?: AdminSmsContactImportFile, csv?: AdminSmsContactImportFile, contacts_file?: AdminSmsContactImportFile, };
