// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardRecentMember = { mb_id?: string, mb_name?: string, mb_nick?: string, mb_level?: number, mb_point?: number, mb_datetime?: string, mb_mailling?: boolean, mb_open?: boolean, email_certified?: boolean, intercepted?: boolean, group_count?: number, };
