// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactImportItem = { name?: string, phone?: string, memo?: string, receipt?: boolean, bk_name?: string, bk_hp?: string, bk_memo?: string, bk_receipt?: boolean, };
