// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminReportItem } from "./AdminReportItem";
import type { Meta } from "./Meta";

export type AdminReportDetailResponse = { data: AdminReportItem, meta: Meta, };
