// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactUpdateRequest = { bg_no?: number, bk_name?: string, bk_hp?: string, bk_receipt?: number, bk_memo?: string, };
