// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSystemMailTemplate = { ma_id: number, ma_subject: string, ma_time: string, ma_ip: string, ma_last_option: string, };
