// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsTemplate } from "./AdminSmsTemplate";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type AdminSmsTemplateListResponse = { data: Array<AdminSmsTemplate>, pagination: Pagination, meta: Meta, };
