// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFieldOptionSource = { kind: string, name: string, endpoint?: string | null, value_field?: string | null, label_field?: string | null, };
