// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPushSendRequest = { title: string, body: string, type?: string, target?: string, member_ids?: Array<string>, };
