// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthLogoutRevoked } from "./AuthLogoutRevoked";

export type AuthLogoutResult = { revoked: AuthLogoutRevoked, logged_out: boolean, };
