// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailabilityCheck } from "./AvailabilityCheck";
import type { Meta } from "./Meta";

export type AvailabilityResponse = { data: AvailabilityCheck, meta?: Meta, };
