// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoardDetail } from "./BoardDetail";
import type { Meta } from "./Meta";

export type BoardDetailResponse = { data: BoardDetail, meta: Meta, };
