// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentItem } from "./ContentItem";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type ContentListResponse = { data: Array<ContentItem>, pagination: Pagination, meta: Meta, };
