// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorGuide = { action?: string, reason?: string, docs?: string, related_fields?: Array<string>, };
