// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthClaimRequest = { transition_token?: string, link_token?: string, mb_id?: string, mb_password?: string, };
