// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthCompleteRequest = { request_token: string, state?: string, code?: string, scenario?: string, payload?: Record<string, unknown>, };
