// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthRegistrationRequest = { transition_token?: string, link_token?: string, mb_id?: string, mb_password?: string, mb_nick?: string, mb_name?: string, mb_email?: string, };
