// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalAuthLinkRecord = { link_id: number, provider: string, provider_user_id: string, mb_id: string, provider_email: string, provider_profile?: Record<string, unknown>, linked_at: string, updated_at: string, };
