// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalAuthLinkRecord } from "./ExternalAuthLinkRecord";

export type ExternalAuthClaimResponseData = { mb_id: string, provider: string, provider_user_id: string, access_token: string, refresh_token: string, expires_in: number, link: ExternalAuthLinkRecord, claimed: boolean, };
