// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqItem } from "./FaqItem";
import type { Meta } from "./Meta";

export type FaqDetailResponse = { data: FaqItem, meta: Meta, };
