// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqMasterImageUploadFile } from "./FaqMasterImageUploadFile";

export type FaqMasterHeaderImageUploadRequest = { file?: FaqMasterImageUploadFile, image?: FaqMasterImageUploadFile, header_image?: FaqMasterImageUploadFile, fm_himg?: FaqMasterImageUploadFile, };
