// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqMasterImageUploadFile } from "./FaqMasterImageUploadFile";

export type FaqMasterFooterImageUploadRequest = { file?: FaqMasterImageUploadFile, image?: FaqMasterImageUploadFile, footer_image?: FaqMasterImageUploadFile, fm_timg?: FaqMasterImageUploadFile, };
