// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FaqImage } from "./FaqImage";

export type FaqMasterDetail = { fm_id: number, fm_subject: string, fm_head_html: string, fm_tail_html: string, fm_mobile_head_html: string, fm_mobile_tail_html: string, fm_order: number, faq_count: number, header_image: FaqImage, footer_image: FaqImage, };
