// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Group = { gr_id: string, gr_subject: string, gr_admin: string, gr_device: string, gr_use_access: number, };
