// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Group } from "./Group";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type GroupListResponse = { data: Array<Group>, pagination: Pagination, meta: Meta, };
