// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";
import type { Meta } from "./Meta";

export type MemberMeResponse = { data: Member, meta: Meta, };
