// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";

export type MemberListResponse = { data: Array<Member>, pagination: Pagination, meta: Meta, };
