// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MenuItem } from "./MenuItem";
import type { Meta } from "./Meta";

export type MenuDetailResponse = { data: MenuItem, meta: Meta, };
