// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../../../g5-admin-models/bindings/serde_json/JsonValue";
import type { Meta } from "./Meta";

export type MessageResponse = { data: JsonValue, meta: Meta, };
