// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pagination = { mode?: string, total?: number, page?: number, per_page?: number, last_page?: number, cursor?: string | null, next_cursor?: string | null, has_next?: boolean, has_prev?: boolean, };
