// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginBoardRewardCommand = { board_id: string, member_id: string, amount: number, reason: string, rel_id?: string, };
