// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBoardRewardResolvedCommand } from "./PluginBoardRewardResolvedCommand";

export type PluginBoardRewardGrantResponse = { plugin: string, mode: string, status: string, reward: PluginBoardRewardResolvedCommand, };
