// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginBoardRewardBoard = { bo_table: string, subject: string, group_id: string, };
