// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBoardRewardBoard } from "./PluginBoardRewardBoard";

export type PluginBoardRewardBoardResponse = { plugin: string, board: PluginBoardRewardBoard, scopes: Array<string>, };
