// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointChangeResult = { mb_id: string, before_point: number, changed_point: number, after_point: number, po_content: string, processed_at: string, };
