// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { PollActiveResult } from "./PollActiveResult";

export type PollActiveResponse = { data: PollActiveResult, meta: Meta, };
