// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PopupCreateRequest = { nw_division?: string, nw_device?: string, nw_begin_time?: string, nw_end_time?: string, nw_disable_hours?: number, nw_left?: number, nw_top?: number, nw_height?: number, nw_width?: number, nw_subject: string, nw_content: string, nw_content_html?: number, };
