// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorGuide } from "./ErrorGuide";
import type { Meta } from "./Meta";

export type ProblemDetails = { type: string, status: number, title: string, detail: string, instance?: string, error_code?: string, error_category?: string, fault_domain?: string, owner?: string, retryable?: boolean, user_actionable?: boolean, request_id?: string, correlation_id?: string, server_request_id?: string, meta?: Meta, guide?: ErrorGuide, errors?: Record<string, unknown>, };
