// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsConfig = { cf_title: string | null, cf_sms_use: string | null, cf_sms_type: string | null, cf_icode_id: string | null, cf_icode_pw: string | null, cf_icode_server_ip: string | null, cf_icode_server_port: string | null, cf_icode_token_key: string | null, cf_phone: string | null, cf_datetime: string | null, provider_ready: boolean, uses_token_key: boolean, uses_legacy_credentials: boolean, storage_ready: boolean, missing_tables: Array<string>, };
