// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Meta } from "./Meta";
import type { Pagination } from "./Pagination";
import type { VisitLogItem } from "./VisitLogItem";

export type VisitSearchResponse = { data: Array<VisitLogItem>, pagination: Pagination, meta: Meta, };
