// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisitStatItem } from "./VisitStatItem";
import type { VisitStatsSummary } from "./VisitStatsSummary";

export type VisitStatsData = { type?: string, summary?: VisitStatsSummary, items?: Array<VisitStatItem>, };
