import { Activity, Coins, FileText, Mail, Search, Trash2, Users, Waypoints } from "lucide-react";
import {
  MEMBER_FILES_ROUTE,
  MEMBER_MAILS_ROUTE,
  MEMBER_MANAGE_ROUTE,
  MEMBER_POINTS_ROUTE,
  MEMBER_POLLS_ROUTE,
  MEMBER_VISIT_DELETE_ROUTE,
  MEMBER_VISIT_SEARCH_ROUTE,
  MEMBER_VISIT_STATS_ROUTE,
} from "../navigation-routes";
import type { NavigationGroup } from "../navigation-types";

export const membersNavigationGroup: NavigationGroup = {
  id: "members",
  label: "회원관리",
  description: "레거시 menu200 회원관리 관리자 축입니다.",
  icon: Users,
  items: [
    {
      to: MEMBER_MANAGE_ROUTE,
      aliases: ["/members"],
      label: "회원관리",
      description: "회원 목록, 상세, 프로필 수정, 레벨 변경을 처리합니다.",
      icon: Users,
      delivery: "implemented",
      legacySource: "adm/member_list.php",
    },
    {
      to: MEMBER_FILES_ROUTE,
      label: "회원관리파일",
      description: "회원 export 파일 생성/다운로드 흐름입니다.",
      icon: FileText,
      delivery: "implemented",
      legacySource: "adm/member_list_exel.php",
      note: "Rust 작업면에서 엑셀용 회원 export 대상 목록을 검색 필드와 함께 조회합니다.",
    },
    {
      to: MEMBER_MAILS_ROUTE,
      label: "회원메일발송",
      description: "회원 대상 메일 발송, 템플릿, 수신자 선택 흐름입니다.",
      icon: Mail,
      delivery: "implemented",
      legacySource: "adm/mail_list.php",
      note: "Rust 작업면은 표준 `/admin/mails` 경로를 기준으로 템플릿 CRUD, 수신자 미리보기, 직접선택 회원 발송을 통합합니다.",
    },
    {
      to: MEMBER_VISIT_STATS_ROUTE,
      label: "접속자집계",
      description: "접속자 통계 집계와 방문 상태 요약 메뉴입니다.",
      icon: Activity,
      delivery: "implemented",
      legacySource: "adm/visit_list.php",
      note: "Rust 작업면에서 집계 유형, 기간, 제한 건수를 바꿔가며 접속 통계를 바로 조회합니다.",
    },
    {
      to: MEMBER_VISIT_SEARCH_ROUTE,
      label: "접속자검색",
      description: "접속 로그 검색과 필터링 메뉴입니다.",
      icon: Search,
      delivery: "implemented",
      legacySource: "adm/visit_search.php",
      note: "Rust 작업면에서 기간, IP, referer, agent 기준 로그 검색과 페이지 이동을 수행합니다.",
    },
    {
      to: MEMBER_VISIT_DELETE_ROUTE,
      label: "접속자로그삭제",
      description: "접속 로그 삭제 작업을 수행합니다.",
      icon: Trash2,
      delivery: "implemented",
      legacySource: "adm/visit_delete.php",
      note: "Rust 작업면은 전체 삭제를 막기 위해 before/date/ip 중 하나 이상 지정해야만 삭제를 허용합니다.",
    },
    {
      to: MEMBER_POINTS_ROUTE,
      label: "포인트관리",
      description: "포인트 내역, 지급, 차감, 만료를 관리합니다.",
      icon: Coins,
      delivery: "implemented",
      legacySource: "adm/point_list.php",
      note: "Rust 작업면은 표준 경로 `/admin/points`와 `/admin/points/summary`를 사용해 목록, 지급, 차감, 만료, 선택 삭제를 함께 다룹니다.",
    },
    {
      to: MEMBER_POLLS_ROUTE,
      aliases: ["/operations/polls"],
      label: "투표관리",
      description: "투표 목록과 CRUD를 처리합니다.",
      icon: Waypoints,
      delivery: "implemented",
      legacySource: "adm/poll_list.php",
      note: "Rust 작업면은 /admin/system/polls 호환 route를 사용합니다. OpenAPI에는 /admin/polls 계열도 함께 존재합니다.",
    },
  ],
};
