export { createSchemaResponse } from "./admin-config-schema-test-fixture";

export function createConfigResponse() {
  return {
    config: {
      cf_title: "그누보드",
      cf_admin: "admin",
      cf_admin_email: "admin@example.com",
      cf_admin_email_name: "운영자",
      cf_register_level: "2",
      cf_register_point: "100",
      cf_login_point: "5",
      cf_use_point: "1",
      cf_write_point: "10",
      cf_comment_point: "2",
      cf_download_point: "-10",
      cf_read_point: "0",
      cf_memo_send_point: "0",
      cf_use_email_certify: "1",
      cf_use_homepage: "0",
      cf_req_homepage: "0",
      cf_use_tel: "1",
      cf_req_tel: "0",
      cf_use_hp: "1",
      cf_req_hp: "0",
      cf_use_addr: "1",
      cf_req_addr: "1",
      cf_new_skin: "basic",
      cf_search_skin: "basic",
      cf_connect_skin: "basic",
      cf_faq_skin: "basic",
      cf_editor: "smarteditor2",
      cf_member_skin: "basic",
      cf_mobile_member_skin: "basic",
      cf_captcha: "kcaptcha",
      cf_social_login_use: "0",
      extra: {
        cf_1: "여분 값 1",
        cf_1_subj: "여분필드 1",
        cf_add_script: "",
        cf_bbs_rewrite: "2",
        cf_cert_use: "1",
        cf_captcha_mp3: "basic",
        cf_email_use: "1",
        cf_email_mb_super_admin: "1",
        cf_email_po_super_admin: "0",
        cf_email_wr_super_admin: "1",
        cf_icon_level: "3",
        cf_member_icon_size: "5000",
        cf_member_img_size: "50000",
        cf_mobile_connect_skin: "basic",
        cf_mobile_faq_skin: "basic",
        cf_mobile_new_skin: "basic",
        cf_mobile_search_skin: "basic",
        cf_open_modify: "0",
        cf_social_servicelist: "naver,kakao",
        cf_sms_use: "icode",
        cf_use_member_icon: "2",
      },
    },
    request_id: "req-config",
    correlation_id: "corr-config",
    server_request_id: null,
  };
}
