export const adminConfigExtraFlagFieldNames = [
  "cf_email_use",
  "cf_email_mb_member",
  "cf_email_mb_super_admin",
  "cf_email_po_super_admin",
  "cf_email_wr_board_admin",
  "cf_email_wr_comment_all",
  "cf_email_wr_group_admin",
  "cf_email_wr_super_admin",
  "cf_email_wr_write",
  "cf_cert_find",
  "cf_cert_req",
  "cf_formmail_is_member",
  "cf_use_profile",
  "cf_req_profile",
  "cf_use_signature",
  "cf_req_signature",
  "cf_use_recommend",
  "cf_use_promotion",
  "cf_use_copy_log",
] as const;

export const adminConfigExtraTextFieldNames = [
  "cf_bbs_rewrite",
  "cf_cert_use",
  "cf_social_servicelist",
  "cf_icon_level",
  "cf_add_script",
  "cf_cert_ipin",
  "cf_cert_hp",
  "cf_cert_simple",
  "cf_cert_use_seed",
  "cf_cert_kcb_cd",
  "cf_cert_kcp_cd",
  "cf_cert_kcp_enckey",
  "cf_cert_kg_cd",
  "cf_cert_kg_mid",
  "cf_cert_limit",
  "cf_login_minutes",
  "cf_recommend_point",
  "cf_cut_name",
  "cf_nick_modify",
  "cf_leave_day",
  "cf_page_rows",
  "cf_write_pages",
  "cf_mobile_page_rows",
  "cf_mobile_pages",
  "cf_captcha_mp3",
  "cf_recaptcha_site_key",
  "cf_recaptcha_secret_key",
  "cf_syndi_token",
  "cf_syndi_except",
  "cf_stipulation",
  "cf_privacy",
  "cf_prohibit_id",
  "cf_prohibit_email",
  "cf_analytics",
  "cf_add_meta",
  "cf_filter",
  "cf_open_modify",
  "cf_possible_ip",
  "cf_intercept_ip",
  "cf_search_part",
  "cf_link_target",
  "cf_1_subj",
  "cf_2_subj",
  "cf_3_subj",
  "cf_4_subj",
  "cf_5_subj",
  "cf_6_subj",
  "cf_7_subj",
  "cf_8_subj",
  "cf_9_subj",
  "cf_10_subj",
  "cf_1",
  "cf_2",
  "cf_3",
  "cf_4",
  "cf_5",
  "cf_6",
  "cf_7",
  "cf_8",
  "cf_9",
  "cf_10",
  "cf_point_term",
  "cf_delay_sec",
  "cf_new_del",
  "cf_memo_del",
  "cf_visit_del",
  "cf_popular_del",
  "cf_new_rows",
  "cf_image_extension",
  "cf_flash_extension",
  "cf_movie_extension",
  "cf_facebook_appid",
  "cf_facebook_secret",
  "cf_twitter_key",
  "cf_twitter_secret",
  "cf_googl_shorturl_apikey",
  "cf_google_clientid",
  "cf_google_secret",
  "cf_kakao_rest_key",
  "cf_kakao_client_secret",
  "cf_kakao_js_apikey",
  "cf_naver_clientid",
  "cf_naver_secret",
  "cf_payco_clientid",
  "cf_payco_secret",
  "cf_icode_server_ip",
  "cf_icode_id",
  "cf_icode_pw",
  "cf_icode_server_port",
  "cf_icode_token_key",
  "cf_sms_use",
  "cf_sms_type",
  "cf_use_member_icon",
  "cf_member_icon_width",
  "cf_member_icon_height",
  "cf_member_icon_size",
  "cf_member_img_width",
  "cf_member_img_height",
  "cf_member_img_size",
  "cf_mobile_new_skin",
  "cf_mobile_search_skin",
  "cf_mobile_connect_skin",
  "cf_mobile_faq_skin",
] as const;

export type AdminConfigExtraFlagFieldName =
  (typeof adminConfigExtraFlagFieldNames)[number];
export type AdminConfigExtraTextFieldName =
  (typeof adminConfigExtraTextFieldNames)[number];

export function isAdminConfigExtraFlagFieldName(
  field: AdminConfigExtraFlagFieldName | AdminConfigExtraTextFieldName,
): field is AdminConfigExtraFlagFieldName {
  return (adminConfigExtraFlagFieldNames as readonly string[]).includes(field);
}

export function isAdminConfigExtraTextFieldName(
  field: AdminConfigExtraFlagFieldName | AdminConfigExtraTextFieldName,
): field is AdminConfigExtraTextFieldName {
  return (adminConfigExtraTextFieldNames as readonly string[]).includes(field);
}

export const adminConfigExtraSections: Array<{
  description: string;
  fields: ReadonlyArray<
    AdminConfigExtraTextFieldName | AdminConfigExtraFlagFieldName
  >;
  id: string;
  title: string;
}> = [
  {
    id: "mail",
    title: "메일/알림",
    description: "메일 발송 사용 여부와 가입/게시글 알림 대상을 관리합니다.",
    fields: [
      "cf_add_script",
      "cf_email_use",
      "cf_email_mb_member",
      "cf_email_mb_super_admin",
      "cf_email_po_super_admin",
      "cf_email_wr_board_admin",
      "cf_email_wr_comment_all",
      "cf_email_wr_group_admin",
      "cf_email_wr_super_admin",
      "cf_email_wr_write",
    ],
  },
  {
    id: "cert",
    title: "본인확인/인증",
    description: "본인확인 사용 여부와 KCB/KCP/KG 인증사 키를 관리합니다.",
    fields: [
      "cf_cert_use",
      "cf_cert_find",
      "cf_cert_simple",
      "cf_cert_use_seed",
      "cf_cert_ipin",
      "cf_cert_hp",
      "cf_cert_kcb_cd",
      "cf_cert_kcp_cd",
      "cf_cert_kcp_enckey",
      "cf_cert_kg_cd",
      "cf_cert_kg_mid",
      "cf_cert_limit",
      "cf_cert_req",
    ],
  },
  {
    id: "member-policy",
    title: "회원/포인트 확장",
    description: "로그인 유지시간, 추천 포인트, 닉네임 변경, 탈퇴 보존 기간 등입니다.",
    fields: [
      "cf_login_minutes",
      "cf_recommend_point",
      "cf_cut_name",
      "cf_nick_modify",
      "cf_leave_day",
      "cf_point_term",
      "cf_delay_sec",
      "cf_new_del",
      "cf_memo_del",
      "cf_visit_del",
      "cf_popular_del",
      "cf_new_rows",
    ],
  },
  {
    id: "skins",
    title: "스킨/페이지",
    description: "페이지 행수와 모바일 전용 스킨/에디터를 세부 조정합니다.",
    fields: [
      "cf_page_rows",
      "cf_write_pages",
      "cf_mobile_page_rows",
      "cf_mobile_pages",
      "cf_mobile_new_skin",
      "cf_mobile_search_skin",
      "cf_mobile_connect_skin",
      "cf_mobile_faq_skin",
    ],
  },
  {
    id: "security",
    title: "보안/약관/필터",
    description: "캡차 리소스, 약관, 금칙어, IP 제한, 검색 정책을 관리합니다.",
    fields: [
      "cf_use_copy_log",
      "cf_captcha_mp3",
      "cf_recaptcha_site_key",
      "cf_recaptcha_secret_key",
      "cf_syndi_token",
      "cf_syndi_except",
      "cf_stipulation",
      "cf_privacy",
      "cf_prohibit_id",
      "cf_prohibit_email",
      "cf_analytics",
      "cf_add_meta",
      "cf_filter",
      "cf_open_modify",
      "cf_possible_ip",
      "cf_intercept_ip",
      "cf_search_part",
      "cf_formmail_is_member",
      "cf_link_target",
      "cf_10",
    ],
  },
  {
    id: "social",
    title: "소셜/확장자",
    description: "소셜 로그인 앱 키와 파일 확장자 허용 목록입니다.",
    fields: [
      "cf_social_servicelist",
      "cf_image_extension",
      "cf_flash_extension",
      "cf_movie_extension",
      "cf_facebook_appid",
      "cf_facebook_secret",
      "cf_twitter_key",
      "cf_twitter_secret",
      "cf_googl_shorturl_apikey",
      "cf_google_clientid",
      "cf_google_secret",
      "cf_kakao_rest_key",
      "cf_kakao_client_secret",
      "cf_kakao_js_apikey",
      "cf_naver_clientid",
      "cf_naver_secret",
      "cf_payco_clientid",
      "cf_payco_secret",
    ],
  },
  {
    id: "sms",
    title: "아이코드/SMS",
    description: "아이코드 접속정보와 SMS 공급자 동작 필드를 그대로 노출합니다.",
    fields: [
      "cf_icode_server_ip",
      "cf_icode_id",
      "cf_icode_pw",
      "cf_icode_server_port",
      "cf_icode_token_key",
      "cf_sms_use",
      "cf_sms_type",
    ],
  },
  {
    id: "profile",
    title: "회원 아이콘/프로필",
    description: "회원 아이콘, 이미지, 프로필/서명 사용 플래그와 크기 설정입니다.",
    fields: [
      "cf_use_member_icon",
      "cf_member_icon_width",
      "cf_member_icon_height",
      "cf_member_icon_size",
      "cf_member_img_width",
      "cf_member_img_height",
      "cf_member_img_size",
      "cf_use_profile",
      "cf_req_profile",
      "cf_use_signature",
      "cf_req_signature",
      "cf_use_recommend",
      "cf_use_promotion",
    ],
  },
];
