export const boardExtraFlagFieldNames = [
  "bo_use_captcha",
  "bo_use_cert",
  "bo_use_dhtml_editor",
  "bo_use_email",
  "bo_use_file_content",
  "bo_use_good",
  "bo_use_nogood",
  "bo_use_ip_view",
  "bo_use_list_content",
  "bo_use_list_file",
  "bo_use_list_view",
  "bo_use_name",
  "bo_use_rss_view",
  "bo_use_search",
  "bo_use_sideview",
  "bo_use_signature",
  "bo_use_sns",
] as const;

export const boardExtraTextFieldNames = [
  "bo_admin",
  "bo_device",
  "bo_list_level",
  "bo_reply_level",
  "bo_upload_level",
  "bo_html_level",
  "bo_link_level",
  "bo_write_point",
  "bo_comment_point",
  "bo_read_point",
  "bo_download_point",
  "bo_gallery_cols",
  "bo_gallery_width",
  "bo_gallery_height",
  "bo_mobile_gallery_width",
  "bo_mobile_gallery_height",
  "bo_image_width",
  "bo_page_rows",
  "bo_mobile_page_rows",
  "bo_subject_len",
  "bo_mobile_subject_len",
  "bo_table_width",
  "bo_mobile_subject",
  "bo_write_min",
  "bo_write_max",
  "bo_comment_min",
  "bo_comment_max",
  "bo_count_delete",
  "bo_count_modify",
  "bo_hot",
  "bo_new",
  "bo_order",
  "bo_include_head",
  "bo_include_tail",
  "bo_content_head",
  "bo_mobile_content_head",
  "bo_content_tail",
  "bo_mobile_content_tail",
  "bo_insert_content",
  "bo_skin",
  "bo_mobile_skin",
  "bo_sort_field",
  "bo_reply_order",
  "bo_select_editor",
  "bo_1_subj",
  "bo_2_subj",
  "bo_3_subj",
  "bo_4_subj",
  "bo_5_subj",
  "bo_6_subj",
  "bo_7_subj",
  "bo_8_subj",
  "bo_9_subj",
  "bo_10_subj",
  "bo_1",
  "bo_2",
  "bo_3",
  "bo_4",
  "bo_5",
  "bo_6",
  "bo_7",
  "bo_8",
  "bo_9",
  "bo_10",
] as const;

export type BoardExtraFlagFieldName = (typeof boardExtraFlagFieldNames)[number];
export type BoardExtraTextFieldName = (typeof boardExtraTextFieldNames)[number];

export function isBoardExtraFlagFieldName(
  field: BoardExtraFlagFieldName | BoardExtraTextFieldName,
): field is BoardExtraFlagFieldName {
  return (boardExtraFlagFieldNames as readonly string[]).includes(field);
}

export function isBoardExtraTextFieldName(
  field: BoardExtraFlagFieldName | BoardExtraTextFieldName,
): field is BoardExtraTextFieldName {
  return (boardExtraTextFieldNames as readonly string[]).includes(field);
}

const boardFieldFallbackLabels: Record<string, string> = {
  bo_table: "게시판 코드",
  bo_subject: "게시판 제목",
  gr_id: "그룹",
  bo_category_list: "분류",
  bo_read_level: "글읽기 권한",
  bo_write_level: "글쓰기 권한",
  bo_comment_level: "댓글쓰기 권한",
  bo_download_level: "다운로드 권한",
  bo_use_category: "분류 사용",
  bo_use_secret: "비밀글 사용",
  bo_upload_count: "파일 업로드 개수",
  bo_upload_size: "파일 업로드 용량",
  bo_sort_field: "리스트 정렬 필드",
};

export function getBoardFieldFallbackLabel(field: string): string {
  return boardFieldFallbackLabels[field] ?? field;
}

export const boardExtraSections: Array<{
  description: string;
  fields: ReadonlyArray<BoardExtraTextFieldName | BoardExtraFlagFieldName>;
  id: string;
  title: string;
}> = [
  {
    id: "policy",
    title: "추가 정책",
    description: "관리자 지정, 접속 기기, 포인트 정책을 함께 조정합니다.",
    fields: [
      "bo_admin",
      "bo_device",
      "bo_write_point",
      "bo_comment_point",
      "bo_read_point",
      "bo_download_point",
    ],
  },
  {
    id: "gallery",
    title: "갤러리/페이지",
    description: "갤러리 너비/높이, 페이지 행수, 모바일 제목 길이 관련 필드입니다.",
    fields: [
      "bo_gallery_cols",
      "bo_gallery_width",
      "bo_gallery_height",
      "bo_mobile_gallery_width",
      "bo_mobile_gallery_height",
      "bo_image_width",
      "bo_page_rows",
      "bo_mobile_page_rows",
      "bo_subject_len",
      "bo_mobile_subject_len",
      "bo_table_width",
      "bo_mobile_subject",
    ],
  },
  {
    id: "limits",
    title: "쓰기 제한/정렬",
    description: "본문 길이, 삭제/수정 제한, 정렬과 에디터 선택 필드입니다.",
    fields: [
      "bo_write_min",
      "bo_write_max",
      "bo_comment_min",
      "bo_comment_max",
      "bo_count_delete",
      "bo_count_modify",
      "bo_hot",
      "bo_new",
      "bo_order",
      "bo_sort_field",
      "bo_reply_order",
      "bo_select_editor",
    ],
  },
  {
    id: "features",
    title: "기능 토글",
    description: "캡챠, 추천/비추천, 검색, 이름/서명 노출 기능을 토글합니다.",
    fields: boardExtraFlagFieldNames,
  },
  {
    id: "includes",
    title: "인클루드/삽입",
    description: "헤더/테일 include와 기본 삽입 본문을 관리합니다.",
    fields: [
      "bo_include_head",
      "bo_include_tail",
      "bo_content_head",
      "bo_mobile_content_head",
      "bo_content_tail",
      "bo_mobile_content_tail",
      "bo_insert_content",
      "bo_skin",
      "bo_mobile_skin",
    ],
  },
  {
    id: "legacy-permissions",
    title: "세부 권한",
    description: "목록·답글·업로드·HTML·링크 권한을 레거시 관리자 계약과 동일하게 관리합니다.",
    fields: [
      "bo_list_level",
      "bo_reply_level",
      "bo_upload_level",
      "bo_html_level",
      "bo_link_level",
    ],
  },
  {
    id: "extra",
    title: "게시판 여분필드",
    description: "여분필드 1~10의 제목과 값을 빠짐없이 관리합니다.",
    fields: [
      "bo_1_subj",
      "bo_1",
      "bo_2_subj",
      "bo_2",
      "bo_3_subj",
      "bo_3",
      "bo_4_subj",
      "bo_4",
      "bo_5_subj",
      "bo_5",
      "bo_6_subj",
      "bo_6",
      "bo_7_subj",
      "bo_7",
      "bo_8_subj",
      "bo_8",
      "bo_9_subj",
      "bo_9",
      "bo_10_subj",
      "bo_10",
    ],
  },
];
