// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqMasterUpdateInput = { fm_id: number, fm_subject: string | null, fm_head_html: string | null, fm_tail_html: string | null, fm_mobile_head_html: string | null, fm_mobile_tail_html: string | null, fm_order: number | null, };
