// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactGroup = { bg_no: number, bg_name: string, bg_count: number, bg_member: number, bg_nomember: number, bg_receipt: number, bg_reject: number, };
