// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPushMessageInput = { title: string, body: string, type: string | null, target: string | null, member_ids: Array<string> | null, };
