// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactExportItem = { bk_name: string, bk_hp: string, bg_no: number, mb_id: string | null, bk_receipt: number, };
