// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSystemMailSendResult } from "./AdminSystemMailSendResult";
import type { ApiTraceMeta } from "./ApiTraceMeta";

export type AdminSystemMailSendResponse = { data: AdminSystemMailSendResult, meta: ApiTraceMeta, };
