// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMemberListQuery = { page: number, per_page: number, search: string | null, search_field: string | null, };
