// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailTestResult = { sent: boolean, mail_log_id: number | null, to: string, };
