// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminThemeConfig = { cf_theme: string, cf_mobile_theme: string, cf_theme_installed: boolean, cf_mobile_theme_installed: boolean, installed_count: number, };
