// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactCreateInput = { bg_no: number, mb_id: string | null, bk_name: string, bk_hp: string, bk_receipt: number, bk_memo: string | null, };
