// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminWriteCountItem } from "./AdminWriteCountItem";
import type { AdminWriteCountSummary } from "./AdminWriteCountSummary";

export type AdminWriteCountStatsResponse = { period: string, date_from: string, date_to: string, bo_table: string | null, summary: AdminWriteCountSummary, items: Array<AdminWriteCountItem>, request_id: string, correlation_id: string, server_request_id: string | null, };
