// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminTheme } from "./AdminTheme";

export type AdminThemeDetailResponse = { theme: AdminTheme, request_id: string, correlation_id: string, server_request_id: string | null, };
