// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqUpdateInput = { fa_id: number, fm_id: number | null, fa_subject: string | null, fa_content: string | null, fa_order: number | null, };
