// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactExportQuery = { bg_no: number | null, include_no_phone: boolean | null, with_hyphen: boolean | null, };
