// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqImage = { exists: boolean, relative_path: string, url: string, width: number | null, height: number | null, mime: string | null, size: number | null, };
