// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsMessageBatchDetailQuery = { wr_no: number, wr_renum: number | null, page: number, per_page: number, search_field: string | null, search: string | null, };
