// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBrowscapStatus = { available: boolean, plugin_path: string, cache_directory: string, cache_file: string, cache_exists: boolean, php_version: string, pending_visit_count: number, updated: boolean | null, cache_mtime: string | null, };
