// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSchemaDetail } from "./AdminSchemaDetail";

export type AdminSchemaDetailResponse = { schema: AdminSchemaDetail, request_id: string, correlation_id: string, server_request_id: string | null, };
