// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsDuplicateSummary } from "./AdminSmsDuplicateSummary";

export type AdminSmsSendResult = { write_no: number, write_renum: number, reply: string | null, message: string | null, booking_at: string | null, total: number, success: number, failure: number, duplicate_summary: AdminSmsDuplicateSummary | null, provider_ready: boolean, };
