// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailRecipient } from "./AdminMailRecipient";
import type { Pagination } from "./Pagination";

export type AdminMailRecipientListResponse = { recipients: Array<AdminMailRecipient>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
