// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthGrant } from "./AdminAuthGrant";

export type AdminAuthUpsertInput = { mb_id: string, auths: Array<AdminAuthGrant>, };
