// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSmsContactImportResult } from "./AdminSmsContactImportResult";

export type AdminSmsContactImportResponse = { result: AdminSmsContactImportResult, request_id: string, correlation_id: string, server_request_id: string | null, };
