// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminTheme } from "./AdminTheme";

export type AdminThemeListResponse = { themes: Array<AdminTheme>, total: number, request_id: string, correlation_id: string, server_request_id: string | null, };
