// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminReportItem = { rp_id: number, mb_id: string | null, rp_target_type: string | null, rp_target_id: string | null, rp_reason: string | null, rp_detail: string | null, rp_status: string | null, rp_admin_memo: string | null, rp_datetime: string | null, rp_processed_at: string | null, };
