// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminSchemaCatalog } from "./AdminSchemaCatalog";

export type AdminSchemaCatalogResponse = { catalog: AdminSchemaCatalog, request_id: string, correlation_id: string, server_request_id: string | null, };
