// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminPoll } from "./AdminPoll";
import type { Pagination } from "./Pagination";

export type AdminPollListResponse = { polls: Array<AdminPoll>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
