// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactBatchInput = { action: string, contact_ids: Array<number>, target_bg_no: number | null, };
