// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailLastOption } from "./AdminMailLastOption";

export type AdminMailDetail = { ma_id: number, ma_subject: string | null, ma_content: string | null, ma_time: string | null, ma_ip: string | null, ma_last_option: string | null, last_option: AdminMailLastOption, preview_html: string | null, };
