// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminDashboardMemberSummary = { total_members: number | null, blocked_members: number | null, leave_members: number | null, };
