// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPhpInfo = { php_version: string, sapi: string, loaded_ini: string | null, scanned_ini: string | null, extension_count: number, html: string, };
