// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqImageUploadInput = { fm_id: number, bytes: Array<number>, file_name: string, mime_type: string | null, };
