// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactItem = { bk_no: number, bg_no: number, bg_name: string | null, mb_id: string | null, bk_name: string, bk_hp: string, bk_receipt: number, bk_datetime: string | null, bk_memo: string | null, receipt_label: string | null, member_type: string | null, member_sync_skipped: boolean | null, };
