// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminLayoutSummary } from "./AdminLayoutSummary";
import type { Pagination } from "./Pagination";

export type AdminLayoutListResponse = { layouts: Array<AdminLayoutSummary>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
