// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminDashboardRecentMember } from "./AdminDashboardRecentMember";
import type { AdminDashboardRecentPoint } from "./AdminDashboardRecentPoint";
import type { AdminDashboardRecentPost } from "./AdminDashboardRecentPost";
import type { AdminDashboardSummary } from "./AdminDashboardSummary";

export type AdminDashboardData = { limit: number | null, summary: AdminDashboardSummary | null, recent_members: Array<AdminDashboardRecentMember>, recent_posts: Array<AdminDashboardRecentPost>, recent_points: Array<AdminDashboardRecentPoint>, };
