// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailSendTarget } from "./AdminMailSendTarget";

export type AdminMailSendResult = { ma_id: number | null, template_used: boolean, target_count: number, sent_count: number, skipped_count: number, mail_enabled: boolean, dry_run: boolean, targets: Array<AdminMailSendTarget>, };
