// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqListQuery = { page: number, per_page: number, fm_id: number | null, };
