// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPopularRankItem = { rank: number, pp_word: string, hit_count: number, first_date: string, last_date: string, };
