// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMailTemplateUpdateInput = { ma_id: number, ma_subject: string, ma_content: string, };
