// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMailTemplate } from "./AdminMailTemplate";
import type { Pagination } from "./Pagination";

export type AdminMailListResponse = { mails: Array<AdminMailTemplate>, pagination: Pagination, request_id: string, correlation_id: string, server_request_id: string | null, };
