// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMemberListItem = { mb_id: string, mb_name: string | null, mb_nick: string | null, mb_email: string | null, mb_level: number | null, mb_point: number | null, mb_datetime: string | null, mb_today_login: string | null, mb_leave_date: string | null, mb_intercept_date: string | null, };
