// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsTemplateGroupUpdateInput = { fg_no: number, fg_name: string | null, fg_member: number | null, };
