// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminMemberMediaUploadInput = { mb_id: string, file_name: string, mime_type: string | null, bytes: Array<number>, };
