// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminDashboardMemberSummary } from "./AdminDashboardMemberSummary";
import type { AdminDashboardPointSummary } from "./AdminDashboardPointSummary";
import type { AdminDashboardPostSummary } from "./AdminDashboardPostSummary";
import type { AdminVisitStatsSummary } from "./AdminVisitStatsSummary";

export type AdminDashboardSummary = { members: AdminDashboardMemberSummary | null, posts: AdminDashboardPostSummary | null, points: AdminDashboardPointSummary | null, visits: AdminVisitStatsSummary | null, };
