// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPermissionListQuery = { page: number, per_page: number, mb_id: string | null, };
