// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPointListQuery = { page: number, per_page: number, mb_id: string | null, search_field: string | null, search: string | null, };
