// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPopup = { nw_id: number, nw_division: string | null, nw_device: string | null, nw_begin_time: string | null, nw_end_time: string | null, nw_disable_hours: number | null, nw_left: number | null, nw_top: number | null, nw_height: number | null, nw_width: number | null, nw_subject: string | null, nw_content: string | null, nw_content_html: number | null, };
