// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminVisitStatsSummary = { total_visits: number, active_days: number, first_date: string | null, last_date: string | null, visit_rows: number, unique_ips: number, };
