// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminMenuReorderItem } from "./AdminMenuReorderItem";

export type AdminMenuReorderInput = { orders: Array<AdminMenuReorderItem>, };
