// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminBoardCopyInput = { bo_table: string, target_bo_table: string, target_bo_subject: string | null, };
