// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsContactSummary = { total_count: number, receipt_count: number, reject_count: number, member_count: number, non_member_count: number, last_synced_at: string | null, };
