// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSmsConfigUpdateInput = { cf_sms_use: string | null, cf_sms_type: string | null, cf_icode_id: string | null, cf_icode_pw: string | null, cf_icode_server_ip: string | null, cf_icode_server_port: string | null, cf_icode_token_key: string | null, cf_phone: string | null, };
