// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminPollUpdateInput = { po_id: number, po_subject: string | null, po_poll1: string | null, po_poll2: string | null, po_poll3: string | null, po_poll4: string | null, po_poll5: string | null, po_poll6: string | null, po_poll7: string | null, po_poll8: string | null, po_poll9: string | null, po_etc: string | null, po_level: number | null, po_point: number | null, po_use: number | null, };
