// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminFaqCreateInput = { fm_id: number, fa_subject: string, fa_content: string, fa_order: number | null, };
