// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminLayoutDetail = { sl_id: number | null, sl_page_id: string, sl_title: string | null, sl_schema: string | null, sl_active: number | null, sl_datetime: string | null, sl_updated: string | null, };
