// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdminAuthGrant } from "./AdminAuthGrant";

export type AdminAuthItem = { mb_id: string, mb_name: string, mb_nick: string, auths: Array<AdminAuthGrant>, };
