// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiTraceMeta = { request_id: string | null, correlation_id: string | null, server_request_id: string | null, server_time: string | null, version: string | null, error_code: string | null, error_category: string | null, fault_domain: string | null, owner: string | null, retryable: boolean | null, user_actionable: boolean | null, };
