// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DebugDevBootstrapStatus = { available: boolean, debug_overlay: boolean, has_master_password: boolean, has_site: boolean, has_site_auth: boolean, site_name: string | null, ssh_profile_count: number, request_id: string, correlation_id: string, server_request_id: string | null, };
