// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MasterPasswordChangeInput = { current_password: string, current_totp_code: string | null, new_password: string, new_password_confirm: string, };
