// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpTransferEnqueueItemInput } from "./SftpTransferEnqueueItemInput";

export type SftpTransferEnqueueInput = { site_id: string, items: Array<SftpTransferEnqueueItemInput>, };
