// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpEntryKind } from "./SftpEntryKind";

export type SftpPathMetadata = { kind: SftpEntryKind, size_bytes: bigint | null, permissions_octal: string | null, modified_at_epoch: bigint | null, };
