// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SftpEntryKind } from "./SftpEntryKind";

export type SftpChmodResponse = { site_id: string, requested_path: string, resolved_path: string, permissions_octal: string, kind: SftpEntryKind, request_id: string, correlation_id: string, server_request_id: string | null, };
