// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecurityStepUpAuthInput } from "./SecurityStepUpAuthInput";

export type SiteBackupExportInput = { path: string, auth: SecurityStepUpAuthInput, backup_password: string, };
