// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SiteBackupImportResult = { path: string, imported_site_count: number, reused_site_count: number, copied_setting_count: number, request_id: string, correlation_id: string, server_request_id: string | null, };
