// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SiteActivityLog } from "./SiteActivityLog";

export type SiteActivityListResponse = { activities: Array<SiteActivityLog>, request_id: string, correlation_id: string, server_request_id: string | null, };
