// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshKnownHostTrustState } from "./SshKnownHostTrustState";

export type SshHostVerificationResponse = { site_id: string, ssh_profile_id: string, host: string, port: number, username: string, server_key_algorithm: string, server_key_fingerprint: string, trust_state: SshKnownHostTrustState, request_id: string, correlation_id: string, server_request_id: string | null, };
