// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAuthType } from "./SshAuthType";

export type SshProfile = { id: string, site_id: string, name: string, host: string, port: number, username: string, auth_type: SshAuthType, key_path: string | null, has_password: boolean, has_key_passphrase: boolean, created_at: string, updated_at: string, };
