// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAuthType } from "./SshAuthType";

export type SshSessionProfileSummary = { ssh_profile_id: string, name: string, host: string, port: number, username: string, auth_type: SshAuthType, };
