// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshSessionProfileSummary } from "./SshSessionProfileSummary";

export type SshSessionStatusResponse = { site_id: string, connected: boolean, shell_open: boolean, active_profile: SshSessionProfileSummary | null, connected_at: string | null, server_key_algorithm: string | null, server_key_fingerprint: string | null, request_id: string, correlation_id: string, server_request_id: string | null, };
